### ISSUE TITLE
Prevent the presence of multiple root path providers from making the bootstrapper throw

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#1125]
- Ignore Nancy.Testing to prevent detecting the FakeRootPathProvider
- Remove the use of `Single()` and decide what should happen is multiple providers are detected

**Comment by bluebaroncanada** [comment]
This helped me out in an unexpected way.  I had launched my instance with a new DefaultBootstrapper.  Changed it to new Bootstrapper().  Took me a while to figure out what was going on because the error kept telling me to override the method and I was like "I have."  and it was like "NO YOU HAVEN'T." and in the end I was like "Okay, you're sorta right."

Putting the error here so people can search for this.

MultipleRootPathProvidersLocatedException

More than one IRootPathProvider was found and since we do not know which one you want to use, you need to override the RootPathProvider property on your bootstrapper and specify which one to use. Sorry for the inconvenience.
