### ISSUE TITLE
When testing, assembly copies made by continuous testing tool causes FileLoadException

### ISSUE THREAD

**Issue by Vidarls** [NancyFx/Nancy#1235]
I use http://continuoustests.com/ for testing and it creates copies of assemblies. These assemblies are attempted loaded by Nancy when scanning for assemblies to load. When they are attemted to be loaded a FileLoadException is thrown:
```
System.TypeInitializationException
The type initializer for 'Nancy.Bootstrapper.AppDomainAssemblyTypeScanner' threw an exception.
   at Nancy.Bootstrapper.AppDomainAssemblyTypeScanner.TypesOf(ScanMode mode)
   at Nancy.Conventions.NancyConventions.BuildDefaultConventions()
   at Nancy.Conventions.NancyConventions..ctor()
   at Nancy.Bootstrapper.NancyBootstrapperBase`1..ctor()
   at Nancy.Bootstrapper.NancyBootstrapperWithRequestContainerBase`1..ctor()
   at Nancy.Testing.ConfigurableBootstrapper..ctor(Action`1 configuration)
   at Nancy.Testing.Browser..ctor(Action`1 action)
The assembly 'file://SomeFile.mm.dll' has already loaded from a different location. It cannot be loaded from a new location within the same appdomain.
```

The reason for the exception is that the content of the file is the same as the assembly currently executing, and thus loaded into the Appdomain.

Could you maybe allow for a blacklist based on filenames, or maybe it's easier to just swallow FileLoadExceptions as was suggested when I discussed the problem in the Nancy Jabbr room.

I'd be more than happy to do the coding, but I feel there should be some discussion on the best solution first.

**Comment by Vidarls** [comment]
Solved or "won't fix"?

**Comment by thecodejunkie** [comment]
@Vidarls Both? Neither? :) We've not seen this being reported from anyone else in 2 years now and neither of us run Continuous Test (though a couple of us run NCrunch without experiencing the exception). Do you know if it still happens with the latest versions of Continuous Test and Nancy? I'm guessing that it loads an assembly into the appdomain when it starts up and then Nancy finds it in the bin-folder and loads it as well. If this is the case then it is a bit of a smell because the test tool is creating a side effect.

I guess as a work around you could set [AppDomainAssemblyTypeScanner.DefaultAssembliesToScan ](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/AppDomainAssemblyTypeScanner.cs#L47) with a custom value that ignored assemblies that contains `.mm.` because I assume it's short for "mighty moose"

Happy to re-open this issue if you think it necessary and help us out to diagnose it (just use the pdb files and step into the place where it is happening) because we lack the proper environment to reproduce it.

Thanks

**Comment by Vidarls** [comment]
I'm happy with workarounds for special case issues :)

It's been some time since I've been doing Nancy projects, but there is one coming up, I'll see how it works out. 

Thanks for taking the time to reply.

**Comment by steve2** [comment]
I just tried downloading Nancy (version 1.4.3) and Nancy.Hosting.Self (version 1.4.1) from NuGet and upon running the sample code (posted below) I got this error.

Code:
```
namespace nancy
{
	class Program
	{
		static void Main( string[] args )
		{
			using( var host = new NancyHost( new Uri( "http://localhost:12345" ) ) )
			{
				host.Start();
				Console.WriteLine( "Running on http://localhost:12345" );
				Console.ReadLine();
			}
		}
	}

	public class Module : NancyModule
	{
		public Module()
		{
			Get[ "/{name}" ] = parameters => "Hello, " + parameters.name;
		}
	}
}
```
