### ISSUE TITLE
Incoming URL is decoded twice (at least with Nancy.Hosting.Self)

### ISSUE THREAD

**Issue by ChrisBrandhorst** [NancyFx/Nancy#1280]
When using `Nancy.Hosting.Self` (at least in this case), an incoming URL is decoded using `HttpUtility.UrlDecode` twice.

First, in `NancyHost.cs#ConvertRequestToNancyRequest`. The resulting `Request` is then passed to the routeresolver, where in `DefaultRouteResolver#ResolveResult`, it is decoded again.

This is a problem when you have URLs like
```
/containers/123/artist/AC%252FDC
```
combined with the following route:
```
/containers/{id}/{filter*}
```
In this case, the `filter` part is a string I would like to split on the slash again (using the slash like this looks nicer in the UI). However, because of the double decoding, the resulting value for `filter` is `AC/DC`, where I would like to have `AC%2FDC`

**Comment by kenotron** [comment]
This is a pretty serious flaw. Why don't we create a UrlPathDecode that is mostly what UrlDecode does in HttpUtility and use THAT inside the parts where you are decoding a path? So, the only thing you need is to modify the DefaultRouteResolver.cs to use that. For everyone else out there, you can get by with this blog's recommendations:

http://programmaticallyspeaking.com/the-mysteriously-escaped-request-path-in-aspnet.html

**Comment by simon-brooke** [comment]
I've hit this bug this morning, and, assuming that double-decoding was going on, tried both:

http://localhost:3579/Json/PointsMatching/%2B

and

http://localhost:3579/Json/PointsMatching/%252B

Both of these were received serverside as spaces, so it's not quite as simple as double-decoding, since double-decoding should decode

'%252B' to '%2B' and subsequently to '+'

I had planned heroically to contribute a patch, but having read through the comments above I see that it's substantially more subtle than I had supposed!

**Comment by taharrison** [comment]
Hey guys.

I just tried to patch the behaviour of url-decoding in DefaultRouteResolver to get around a bug with the treatment of encoded `/`s.  But I've closed my pull request, because it relied on the DefaultRouteResolver being responsible for URL Decoding, which from the discussion here it seems it shouldn't be.

I carefully documented the issues I saw though, so am reproducing the summary and test cases here so that they can help inform future work on this issue:

> Currently the DefaultRouteResolver url-decodes capture groups before identifying where the capture groups begin and end (i.e. splitting on "/")
>
> This leads to odd behavior around encoded "/"s.

> Examples:
> 
> With routes
> 
> "foo/{bar}/baz"
> "foo/{fuzz}"
>
> a request to "foo/bar%2fbaz" will resolve to route "foo/{bar}/baz", despite the "/" having been encoded (and should therefore not be treated as a path separator).
> 
> a request to "foo/3-slashes-looks-like-"%2f%2f%2f" resolves to "foo/{fuzz*}" (but not "foo/{fuzz}") with a Fuzz parameter initialised to "3-slashes-looks-like-"/"", rather than the expected "3-slashes-looks-like-"///""
>
> The fix is to delay url decoding until /after/ the path has been split on the "/" characters.

The following tests demonstrated the above behaviour as part of `DefaultRouteResolverFixture`

The first 4 demonstrate current incorrect behaviour around encoded "/"; the last 5 demonstrate current supported behaviour around url decoding /within DefaultRouteResolver/.

        [Theory]
        [InlineData("/bleh/test%2fbar", "GreedyOnEnd", "test/bar")]
        [InlineData("/foo/test%2ffuzz/plop", "Captured", "test/fuzz")]
        [InlineData("/bleh/test%2f%2ffuzz/bar", "GreedyInMiddle", "test//fuzz")]
        [InlineData("/foo/%21%23%24%26%27%28%29%2A%2B%2C%2F%3A%3B%3D%3F%40%5B%5D/plop", "Captured", "!#$&'()*+,/:;=?@[]")]
        public void Should_resolve_and_decode_capture_groups_with_encoded_forward_slashes(string path, string captureType, string expected)
        {
            //Given, When
            var browser = InitBrowser(true);
            var result = browser.Get(path);

            //Then
            result.Body.AsString().ShouldEqual(captureType + " " + expected);
        }

        [Theory]
         [InlineData("/bleh/this%2fis%2fsome%2fstuff/bar", "GreedyInMiddle", "this/is/some/stuff")]
         [InlineData("/bleh/this%2Fis%2Fsome%2Fstuff/bar", "GreedyInMiddle", "this/is/some/stuff")]
         [InlineData("/foo/double%252fencoded/plop", "Captured", "double%2fencoded")]
         [InlineData("/foo/%61%62%63%31%32%33/plop", "Captured", "abc123")]
         [InlineData("/foo/%21%23%24%26%27%28%29%2A%2B%2C%3A%3B%3D%3F%40%5B%5D/plop", "Captured", "!#$&'()*+,:;=?@[]")]
         public void Should_url_decode_captures(string path, string captureType, string expected)
         {
             //Given, When
             var browser = InitBrowser(true);
             var result = browser.Get(path);
 
             //Then
             result.Body.AsString().ShouldEqual(captureType + " " + expected);
         }

**Comment by thecodejunkie** [comment]
This is unsolveable .. all framework suffer from this on all platforms
