### ISSUE TITLE
NancyHost should reflect Internal Children of NancyModule

### ISSUE THREAD

**Issue by zippy1981** [NancyFx/Nancy#1302]
I know this goes against a lot of conventions, but there is no reason my route modules needs to be public. I  am a scope nazi, so I expect `internal sealed class Something : NancyModule{}` to be picked up by my nancy host.

**Comment by vchekan** [comment]
How possible this works: this.modules is private and can not be used in override?

Besides it seems to me rather inconvenient to dig into details of ioc implementation for such a common use case.

**Comment by phillip-haydon** [comment]
@vchekan it's not a common use case at all. In neither Nancy or MVC, to need to load modules after the application has started.

**Comment by jbuechner** [comment]
The previously posted code example comes from my own implementation of a NancyBootstrapper (derived from NancyBootstrapperBase). As you mentioned the modules field is private in NancyBootstrapperBase.

In my own derivative bootstrapper I just declared a private field named modules. The private field from the NancyBootstrapperBase is not affected by it. The private modules field is only used to implement a lazy property in both, my own and the base implementation.

**Comment by vchekan** [comment]
@phillip-haydon than I must be missing something. I do not load module after app load. My use case is as basic as it gets: provide REST service in windows service process. I followed the examples in documentation and created a module class in my project:

    public class RestServer : NancyModule
    {
        public RestServer(TaskRunnerHost host) {
            Get["/tasks"] = _ => Response.AsJson(host.Discovery.Tasks.Select(ShowTask));

Obviously I declared this class as internal at first and it didn't work, the path "/tasks" gave 404 error. When I declared it public, it worked, but now I have another problem, my constructor parameter, TaskRunnerHost  is internal structure not intended to be exposed at all, Yet I have to make it public too.

I suspect you are talking about some way of explicit declaration of nancy modules instead of relaying on reflection discovery? Is it explicit registration in IoC?

Also, documentation says:

    Nancy will scan and identify all types that are descendants of the NancyModule type

Which is incorrect.

**Comment by jbuechner** [comment]
The documentation is not really clear in this case, as Nancy is only looking for public types of NancyModule.

If you already have your own bootstrapper for your nancy application you can use the code from above. Beside overloading the Module property you have to add an `IEnumerable<ModuleRegistration> module;` member to your bootstrapper to make it work.

**Comment by vchekan** [comment]
Another documentation error is that nancy is looking up INancyModule and not NancyModule derived classes.

I am surprised that Nancy is not using IoC for resolving modules. I tried to register my own module, but without any success. 

        protected override void ConfigureApplicationContainer(TinyIoCContainer container)
        {
            container.Register<INancyModule>(new RestServer(_host));
        }


I also tried to override Modules and do 

    base.Modules.Concatenate(new[] {new ModuleRegistration(typeof(MyModule))})
But I rolled it back because I am not sure that this new registration is not called on each request, thus creating new registrations on every call.

I could dive into nancy-specific DI engine, but I feel it is way too complicated for something so simple and it would be direct contractiction to the-super-duper-happy-path:
https://github.com/NancyFx/Nancy/wiki/Introduction#the-super-duper-happy-path

**Comment by phillip-haydon** [comment]
I don't really follow.

You want to have Private/Internal Modules and Dependencies?

**Comment by vchekan** [comment]
I want as simple as possible REST service in single assembly scenario. Internal Module with explicit instantiation would be preferred. I do not really need dependency Injection. Something like this (pseudocode):

    main() {
       new NancyHost("/myapp", new MyNancyModule(someParamsHere))

    class MyNancyModule : NancyModule {
      internal MyNancyModule(string someParam) {
    ...

I really would like to avoid DI until I really need it.

**Comment by jbuechner** [comment]
If you use the first approach, you'd only be able to register a single INancyModule in the whole container (this is typically not what you want :) ).

Your concerns with the second approach are correct. You can't be certain if the Modules property on a Bootstrapper is used only once. But you can change your concatenation in the Modules getter so you can be certain.

```c#
        IEnumerable<ModuleRegistration> modules;
        protected override IEnumerable<ModuleRegistration> Modules
        {
            get
            {
                if (modules == null)
                    modules = base.Modules.Concat(new[] { new ModuleRegistration(typeof(MyModule)) }).ToList();
                return modules;
            }
        }
```

I assume the SDHP can only work with some assumptions ( e. g. all NancyModules being public ).

**Comment by vchekan** [comment]
Yeah, but my next best approach would be Nancy to use DI to resolve modules in addition to scanning assemblies:


    protected override void ConfigureApplicationContainer(TinyIoCContainer container)
    {
        container.Register<INancyModule>(new RestServerModule(_host));
    }

**Comment by jbuechner** [comment]
I don't know if its possible or not. Because the `Module` property inside a Bootstrapper returns `ModuleRegistration` instances. A ModuleRegistration is a sealed class returning the *type* of a module, not an instance.
Using `Register` on a tiny ioc registers a single instance with a certain registration type. Meaning your module is instantiated before the nancy application has been bootstrapped. This can lead to issues when you need to inject certain nancy functionality in your module (because you can't be certain that they will be available inside the application container before the bootstrapper has finished its work).

**Comment by damianh** [comment]
Overriding `protected override IEnumerable<ModuleRegistration> Modules { get; }` is the way to let Nancy know about modules it won't find via scaning e.g. internal ones. Personally, I do this as standard practice.

Nancy needs to activate your modules and it will only do so through a container (TinyIoC, or your own)

The module constructors should be public though as that is the only way TinyIoC supports ([for good reasons too](https://github.com/grumpydev/TinyIoC/issues/71)). This should not force the types that are injected to be public if the class is public.
