### ISSUE TITLE
Allow Actions to be Resolved

### ISSUE THREAD

**Issue by atrauzzi** [NancyFx/Nancy#1413]
Right now in Nancy, if I write a route, I have to use a lambda or something that looks like one:

```
Get["/"] = _ => { /* ... */ };
// Or
Get["/] = AnotherMethodInSameClass;
```

(It also seems to be that actions live inside the same module in which it's defined, or it's one module per action.)

If I'm defining routing for a large application, it's possible that I might be creating quite a few to handle all the different paths I need.  With the way routing is right now, each route's handler has to be a living instance of an object.  
For apps that use dependency injection, this means that every dependency of every module will end up being instantiated just so that they can supply their actions to the routes.

It is however conceivable that a route could do the following:

```
Get["/"] = _ => {
    var controller = MyIoC.Resolve<MyController>();
    return controller.homeAction(_);
};
```

But I think it's no surprise that we'd all get tired of writing that every time just to define our routes, and the _happy path might start to get a bit overgrown_.

If there isn't a provision for it already, I think the action part of a route should be `dynamic` and Nancy should allow people to write their own action resolver based on the type of the value supplied by the module.

This would allow me to write code as follows:

```
Get["/"] = typeof(MyProject.Controller.Home);
```

And if I'm feeling really creative with my resolver:

```
Get["/user/profile"] = {typeof(MyProject.Controller.User), "some way of indicating the method to run"};
```

Nancy could ship with it's own default lambda resolver configured which would preserve default functionality.  Then people could write handlers for the different IoC packages out there so that actions can be resolved only when they're run.

**Comment by tytusse** [comment]
Let's rephrase the main issue here.
In 1.4.3 release you have this inside constructor of RouteCache (RouteCache.cs line 41):
```
using (var context = contextFactory.Create(request))
{
   this.BuildCache(moduleCatalog.GetAllModules(context));
}
```
This code is called every time application starts to populate route cache. It constructs all modules in order to get routes from them.

Imagine, that you have module like this, registered as "per web request" (default behavior of auto register I think):
```
public class MyModule : NancyModule {
   public MyModule(IDbconnection conn) {
      Get["/"] = props => conn (...... some query to database ....)
   }
}
```
Note the `IDbconnection conn` here - let's assume that this is also as 'per web request'. Intention is to have some dependencies automatically created and destroyed 'around' request. 

Consequence of above setup is that during app start the `conn` object is created and destroyed, without being used. Now imagine, that we have more such modules and dependencies. We have really long app start to begin with simply because the design of NancyModule is as it is. Some people will say "so what", but still ...

What is the suggested "best practice" here? Service locator inside module? ;-)
```
public class BetterNancyModule: NancyModule {
   public BetterNancyModule(IocContainer container) {
      Get["/"] = props => container.Resolve<IDbConnection>().......
   }
}
```
This question is somewhat related to plain old rust of ASP.NET MVC and how it works in this respect: there you have Controllers in place of Modules, and you put dependencies in Controllers, routes as methods etc. Difference is that it will not create controllers to scan routes.

**Comment by atrauzzi** [comment]
Phew!  This is a pretty old bone to dig up.

@tytusse - Thanks so much for taking another stab at the explanation, I think you definitely understand my original concern!
Honestly though, based on the attitude in the *very first* response I got to this ticket, I blacklisted nancy from my tech list.  Three years later and asp.net core is much better than nancy, with a far more welcoming community.

**Comment by nathan-alden** [comment]
@atrauzzi Unfortunately, you never showed _why_ it's such a big deal to avoid module instantiation, even if it is just to create routes. In a properly architected application, module instantiation should be nearly free in that the module constructors don't perform any complex or intensive logic. Even if the module class has additional dependencies injected into its constructor, those dependencies' constructors should themselves be lightweight if following SOLID principles.

I can see you point with regards to decoupling route definitions from module instantiation. It can be argued that there is a tight coupling in Nancy's design at the moment. However, I find it hard to believe there are realistic scenarios where instantiating every module in order to define its routes presents a severe startup performance penalty. Do you have data to go with your original complaint? Perhaps you ran into a legitimate performance issue that needed addressing.

As far as blacklisting Nancy, that's an unfortunate decision. I recommend you take another look. FWIW, I am not a Nancy contributor, but I am a big fan of the framework. Its abstractions are far closer to those needed by HTTP APIs than what Microsoft provided with ASP.NET Core MVC. I wrote a lot of customizations to Web API 2 in order to get it to fit some pretty interesting scenarios, and migrating those abstractions to Core MVC proved to be either difficult or flat-out impossible. When I tried the same thing in Nancy, I met much less resistance on every point. Nancy _just works_ and doesn't fight HTTP--it embraces it.

I have found the Nancy community very welcoming. In fact, the official Nancy Slack channel has become sort of a "home" for me to just discuss general software development topics, not just for technical Nancy help. The Nancy contributors are friendly and willing to listen to reasoned arguments. Put your ego aside and give them another chance.

**Comment by atrauzzi** [comment]
@nathan-alden - I did well enough explaining it, there are countless other frameworks that don't question the practice.  Especially not as derisively as was handled here, if there's no willingness to listen, no amount of explanation will help.

The use case is simple: Every other framework doesn't do it and they are quite reasoned about why.  I see one shouldn't want to instantiate every "module" (in nancy's case).  It's the same as why I don't want every controller (full of actions) instantiated in MVC.  You build and inject it on demand (especially because injections may vary at runtime/request time).  There are other reasons, if nancy wants to buck conventional wisdom on this, it's either for good or no reason what so ever.

All of that is talking past the real issue and the rest of your excuses really exemplify the attitude that I found so repulsive in this project.  _My ego?  Reasoned arguments?_  Such asinine and aggressive things to say.

I've encountered far less ornery behaviour discussing ideas at other projects.  And I've succeeded in conveying ideas.

Take *your* ego out of it and don't involve mine against my wishes.

**Comment by phillip-haydon** [comment]
@atrauzzi I don't really know what your problem is. The issue originally raised is known and by design. Modules are created once during startup so they are known, and cached. Once started, a module is only ever re-created when it's needed in order to for fill a request. It seems that you don't like the way we discover modules and routes. 

> For apps that use dependency injection, this means that every dependency of every module will end up being instantiated just so that they can supply their actions to the routes.

This makes it sound like we create every module on every request which is simply not true. Only the module that matches the route will be created in order to for fill the request. If you have dependencies on a module for routes that don't require that dependency, then you probably need to rethink your module as it's clearly doing more than 1 thing. 


Anyway this thread is going to go around in circles. You've made your case. We have explained to you why we consider it a non-issue. I'll lock this thread as there is nothing more that can be contributed.
