### ISSUE TITLE
Generating API documentation

### ISSUE THREAD

**Issue by mat-mcloughlin** [NancyFx/Nancy#1486]
Just opening up an issue so we can discuss the possibility of having Nancy generate documentation for the applications built using it. 

As an example of how this is done in our beloved Web API see here http://www.asp.net/web-api/overview/creating-web-apis/creating-api-help-pages

**Comment by Corstiaan84** [comment]
Hi guys. I am doing some prep for a new project. Really want to use Nancy again but the api docs are an important part of the new project. Like @agasthyanavaneeth I am also interested in the status of all things Swagger 2.0. Any news? :-)

**Comment by khellang** [comment]
@Corstiaan84 There is a PR going for Swagger 2.0; https://github.com/khellang/Nancy.Swagger/pull/64.

**Comment by Corstiaan84** [comment]
@khellang cool, thanks

**Comment by khellang** [comment]
OK, I think it's time for me to put [Nancy.Swagger](https://github.com/khellang/Nancy.Swagger) up for adoption.

Here are my reasons:

I'm not using Nancy much for production (read; work) stuff anymore. Quite frankly, I don't do much server-side web *at all* ATM, so I've lost some interest :disappointed: 

I also lost quite a bit of steam realizing how much frickin' work it takes to get some decent metadata out of Nancy, simply because of its dynamic nature. Everything has to be explicitly declared, hand-holding the framework every step of the way, and I don't see this changing. Not very SDHP! :stuck_out_tongue_winking_eye:

And finally; time is a scarse, invaluable resource, and there are tons of things to do. Based on the above, I've concluded that spending huge amounts of my time on Nancy.Swagger is not really what I want. It's not fair to anyone that the project just sits there because I don't have interest or cycles to spend on it.

So... If someone would like to keep working on it, or simply scrap it altogether and use the name for a new project, just shout out, and I'll transfer the repository and NuGet package owner rights. :smile:

Thanks!

**Comment by jchannon** [comment]
Please don't scrap it etc as we use it for our API documentation and use the nuget libs :smile:

**Comment by xlegalles** [comment]
Hi, so what is the status of this request? My company is currently starting the development of a project based on a microservices architecture. Nancy is a very good candidate for backend services but we all know that it is mandatory to be able to document/expose the REST API. And Swagger is a nice tool to do it. I don't like Nancy.Swagger with seperate modules because it is the best way to have it disconnected from the implementation. I would really prefer what @liddellj suggests and have the option to augment the metadata at the point a route is defined.
Honestly, if we can't document a Nancy API other than using Hypermedia Controls, we will certainly reconsider our choice and use ASP.Net. Too bad :(
Thank you for your answer
