### ISSUE TITLE
application pipelines.BeforeRequest not called when request from Diagnostics

### ISSUE THREAD

**Issue by LarsDK** [NancyFx/Nancy#1664]
Well, not the best title, couldn't come up with something better.

The issue is that when accessing http://localhost:50526/_Nancy/, my callback for the BeforeRequest isn't called, but my callback for the AfterRequest is called correct.
When I access every other route in my app the BeforeRequest callback is called correct.

**Comment by jruizaranguren** [comment]
I am experiencing the same problem. Additional info: 

### Steps to Reproduce

* Add a BeforeRequest hook.
* Configure Diagnostics. In my case, I choose the path `admin/dashboard`.
* Debug or launch application.

The  BeforeRequest hook is not called for ~/admin/dashboard route.

### System Configuration
- Nancy version: 1.4.3.
- Nancy host ASP.NET + OWIN.
- .NET 4.5.2.
- Windows 7.

**Comment by khellang** [comment]
Hmm. On the phone, so haven't checked, but could this be because the diagnotics itself is implemented as a before-hook? How are you adding the hook? To the end or yhe start of the pipeline?

**Comment by jruizaranguren** [comment]
No matter I add it at start, end or specific index. My hook is never called.

**Comment by thecodejunkie** [comment]
@jruizaranguren this is working "as intended" in `1.4.3` since when you hit a diagnostics route, we do not expect to run any user-code. The `ApplicationStartup` is executed before the diagnostics stuff is wired into the Before-pipeline, so even if you where to do `pipelines.BeforeRequest.AddItemToStartOfPipeline(...)` it would still be added after diagnostics. This is probably not something we are likely to change for `1.4.x` as it would break others that would rely on this behavior.

What kind of code do you want to run even for diagnostics routes? The before-hook is intended to return a `Response` to the user, even though you can hotwire it for things like logging if you wanted to. For `2.x` I have some ideas to change diagnostics and this could be added to the wish-list. Would help us if we understood the scenario you are trying to cover

**Comment by jruizaranguren** [comment]
We are given a legacy non-standard authentication system that we have to use. We can not use it to apply route-based authorization rules. Instead, it provides us with user claims that we can retrieve by de-encrypting a token. We have implemented those authorization rules as a `BeforeRequest` hook.

We wanted the Nancy Dashboard, and other admin-related routes to be allowed only if some claims provided by our authentication system are found (instead of the super-secure admin hard-coded password :smile:  ). 

Summarizing, it is just a matter of being able to protect dashboard features through an authentication system.

**Comment by khellang** [comment]
What if you add the hook to the start of the pipeline in `RequestStartup` instead? I think that would make it appear before the diagnostics hook, which means you should be able to inspect the request and optionally short-circuit the pipeline by returning a response.

**Comment by thecodejunkie** [comment]
@khellang @jruizaranguren yes, that would be my suggestion as well. Just keep in mind that this will happen for all requests, which generally is not a problem. However for diagnostics there is going to be a lot of requests since it is embedded in Nancy itself so it will make requests, to itself, in order to get all the assets etc that it needs. So when you load a diagnostics page you might end up with about 10-11 requests going back (it's getting a bunch of js and css files). I only point this out if you have any expensive object instantiation etc. in which case you should factor it in and do what you can to mitigate the cost

**Comment by khellang** [comment]
@thecodejunkie Are those not handled by static files? Or does diagnotics do something special for embedded resources?

**Comment by thecodejunkie** [comment]
@khellang yeah diagnostics hijacks all requests that match the URL

**Comment by jruizaranguren** [comment]
Great.
@khellang , @thecodejunkie, thank you very much for your Premium Support.
