### ISSUE TITLE
Upgrade build scripts to Albacore 2.0

### ISSUE THREAD

**Issue by haf** [NancyFx/Nancy#1686]
Hi,

You've been users of albacore for a long time; I suggest you to upgrade to v2.0 and bring back this project to the fold. We're very open to pull requests and it would be great to have the scrutiny of another large popular .Net project that compiles for both Windows and Mono.

**Comment by beachwalker** [comment]
Can't build even with older version of  Albacore (1.0)

used this command for instlallation: gem install albacore --version "~>1.0.0"

![image](https://cloud.githubusercontent.com/assets/2715897/5988491/8c6d93f8-a962-11e4-9cbf-36988a324077.png)

... but the build tries to resolve Release|HPD configuration wihin VS and can't find this configuration.

When using the current Albacore 2.3 I can't even run the script:

![image](https://cloud.githubusercontent.com/assets/2715897/5988508/57b9fe02-a963-11e4-8574-406dfd71a541.png)

We use nuget packages to include project dependencies but we are currently unable to use them because Nancy 0.2x series had a missing feature that successfully. Luckyly this feature arrived in 1.0 but Nancy is also unable to serve static files in the 1.0 release (worked in 0.2x).

So we have these options:

- Try to find and solve the problem... then build the packge (=> currently the rake scripts not working so we have no packages)
- Integrate Nancy as Lib without Nuget (=> don't like this solution, did that in the past)
- Try to grab a latest package from other CI servers which can build the package including the fix for static files (where to get the "latest build" nuget packages?)
- Build a workaround using OWIN for static files => some said it's working this way... but why, what about the super duper happy path ;-)
...

**Comment by haf** [comment]
From major version 1.0 to version 2.0 the API is different, so you'd have to change the script first. See albacore's wiki, but I think there are already some progress towards using 2.0 in a PR somewhere by Daniel.

As for the first error, it's not an albacore error, but an MsBuild error. See what MsBuild command line is being invoked and fix that error.

**Comment by thecodejunkie** [comment]
I think there were some major pains to upgrade to v2.x so we've not really bothered (bigger fish to fry, not enough gain and things like that). We would ofc be happy to take a pull-request that performed the upgrade (we would in the long run have to update all other repos as well since we use RAKE for them as well)

**Comment by tparnell8** [comment]
is anyone tackling this? I'd love to take it on. I am a fairly big fan of Ruby and Albacore

**Comment by phillip-haydon** [comment]
@tparnell8 nope, based on what @thecodejunkie said, you're free to do it. :)

**Comment by grumpydev** [comment]
Just bear in mind that Nancy.Build has the repo with the main build script of doom in it 😊

**Comment by tparnell8** [comment]
Alright I'd be down for a challenge.

**Comment by tparnell8** [comment]
So I started working on this a little, but I keep getting side tracked by life, and other things. So I'm going to have to throw this back, because otherwise its going to take me another month or so before I will have a PR. Sorry everyone!

**Comment by adamralph** [comment]
I guess this is invalid now, given #2484?

**Comment by damianh** [comment]
It is invalid. Closing.
