### ISSUE TITLE
Regex routing not working for following example.

### ISSUE THREAD

**Issue by nilayparikh** [NancyFx/Nancy#1722]
I'm trying to create generic route for category page,

My current Regex for evaluation,

    \/[\w\/\-\%]+-c(\d+)(?:\/(\d{1,2}))?$

Controller code,

    Get[@"\/[\w\/\-\%]+-c(?<id>\d+)(?:\/(?<page>\d{1,2}))?$", true] = async (x, ct) =>
    {
      ...
    }

I'm trying with RegExr tool and it seems to be passing all possible permutation and combinations for the regex,

    i.e /anytgc123423/test/c123323/niec454stest/mystery-123-4534-thriller-suspense-c79/11

    Result:
    Group 1: 79 
    Group 2: 11

The same regex is not able to parse the url suggested in example with NancyFx Get function.

To be sure on my code, I have tried to test below sample code,

    var categoryRegex = @"\/[\w\/\-\%]+-c(?<id>\d+)(?:\/(?<page>\d{1,2}))?$";
    var categoryURL = "/anytgc123423/test/c123323/niec454stest/mystery-123-4534-thriller-suspense-c79/11";
            
    var match = Regex.Match(categoryURL, categoryRegex);
    var id = match.Groups["id"];
    var page = match.Groups["page"]; 

The code worked like charm.

It would be great help if anyone can throw some light.

Apologies for my bad English, and thanks in advance.

**Comment by phillip-haydon** [comment]
The example above wouldn't work because it doesn't conform to the way we handle regular expressions in routes.

Greedy Regex routes need to begin with `^(` and end with `)$` or `)`, while Regex routes must start with `(` and end with `)`.

https://github.com/NancyFx/Nancy/wiki/Defining-routes

At a glance I would assume your route needs to look like;

`^(?:\/[\w\/\-\%]+-c(?<id>\d+)(?:\/(?<page>\d{1,2}))?)$`
