### ISSUE TITLE
Add Guid to Token authentication?

### ISSUE THREAD

**Issue by Corstiaan84** [NancyFx/Nancy#1731]
Any particular reason why user guid's are not integrated with Authenication.Token, as they are with Authentication.Forms? If not, I would consider this a good addition :+1:

**Comment by iYalovoy** [comment]
Because nancy doesn't force you what kind of identifier to use to define your users. In case of Authentication.Forms they use guid to identify user, because to use username is too risky, but at the same time it doesn't mean this guid has to be your primary guid for users, you can use it as reference authentication guid. In case of Authenication.Token there is no need to use any guid, so they don't.
Sidenote.
https://github.com/NancyFx/Nancy/wiki/Token-Authentication
Docs say
**It is recommended that you configure the Tokenizer to use an additional piece of information that can uniquely identify the client device.**
So, actually they welcome you to put your user id there.
