### ISSUE TITLE
GetModuleTypes virtual not found

### ISSUE THREAD

**Issue by rbirkby** [NancyFx/Nancy#1769]
The [wiki](https://github.com/NancyFx/Nancy/wiki/Bootstrapping-nancy#user-content-part-1---customisation-options) says I can override GetModuleTypes to customise module loading. But this method doesn't appear to exist.

In fact, the only place I can find it is in a 2011 [gist](https://gist.github.com/thecodejunkie/825827#file-nancybootstrapperbase-cs)

**Comment by cjbush** [comment]
Seconded. Update the documentation please. It APPEARS that the proper overload is now the "Modules" property inherited from NancyBootstrapperBase.

**Comment by khellang** [comment]
Just an FYI; anyone can update the documentation :smile:

**Comment by cjbush** [comment]
True! Is my hunch correct regarding the Modules property? If so I'll be happy to update it.

**Comment by khellang** [comment]
Yep. You have to override the `Modules` property and return an `IEnumerable<ModuleRegistration>`. It's basically the module types wrapped in `ModuleRegistration` (and old type that no longer serves a purpose and really should be cut).

**Comment by cjbush** [comment]
In a slightly related question, is there a way to modify the way Nancy scans and loads assemblies at startup? I'd like to be able to load an assembly without locking the dll, so that I can basically do a swap on the fly and then just restart my self host server without restarting the wrapper process. Kind of like an on-the-fly update. I think I could accomplish this by having Nancy load the assembly bytes rather than the assembly itself, but I'm not sure if AppDomainAssemblyTypeScanner and company are overridable or not.

**Comment by grumpydev** [comment]
No, it doesn't support that and I'm not sure that would work anyway - you can't unload assemblies from an appdomain so you'd end up with duplicates if you loaded the same thing again. The best way to do this is to spin up your own appdomain inside your own wrapper process and run the self host in that, then you can tear it down and restart it without stopping the wrapper.

**Comment by glenserraview** [comment]
I updated the wiki - basically just changed "GetModuleTypes" to "Modules"
