### ISSUE TITLE
usual string parameters in request instead DynamicDictionary

### ISSUE THREAD

**Issue by barabaz-z-z** [NancyFx/Nancy#1773]
Good day.

How can I generate routing without parameters of dynamic type?

Here https://github.com/NancyFx/Nancy/wiki/Taking-a-look-at-the-DynamicDictionary
In last but one paragraph you say about usual properties. Could you give me some explanation about this properties. How can I use it? Example? Does it change dynamic type?

**Comment by Crisfole** [comment]
That comment is not about statically typed properties, it's about using the indexer syntax rather than the property-name syntax:

    p["name"]

vs

    p.name

To my knowledge it is impossible to use Nancy w/out dynamic parameters.  But then again, you're getting a string in the first place, so dynamic is quite appropriate.  The way I usually use Nancy involves the Module as the only place where I consider `dynamic` to be appropriate. My first step is always to `Bind` to a static type and pull out (and cast to a specific type) all route values.

**Comment by barabaz-z-z** [comment]
Thanks a lot. I will be aware of it.
