### ISSUE TITLE
Malformed token header causes RequiresAuthentication to throw a RouteExecutionEarlyExitException

### ISSUE THREAD

**Issue by delaneyj** [NancyFx/Nancy#1785]
Using a token as describe in https://github.com/NancyFx/Nancy/wiki/Token-Authentication works wonderfully.  
`Authentication : Token ZGVtbw0KZGVtb3xhZG1pbg0KNjM1NTczMTIwNTgy=`

However a malformed one 
````Authentication : T ZGVtbw0KZGVtb3xhZG1pbg0KNjM1NTczMTIwNTgy=`

Causes a `RouteExecutionEarlyExitException` on `this.RequiresAuthentication();` line.  

Is this correct?  If then token isn't valid a 500 code is send back with info about incorrect base64 encoding.  Should calls to RequireAuth/Claims be wrapped in try/catch blocks?

**Comment by khellang** [comment]
I definitely think a malformed header should be a 400 and not a 500, but I think this particular scenario should be handled at a header parsing level, not in the authentication. BTW, do you have any clue why the token auth doesn't do an early return [here](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Authentication.Token/TokenAuthentication.cs#L99)? The scheme doesn't match at all.

**Comment by khellang** [comment]
Oh, right. I see what you're saying now. The `RouteExecutionEarlyExitException` is how Nancy handles `this.RequiresAuthentication()` calls inside a route handler. That's meant to happen because the user hasn't been authenticated. I think the `Detokenize` call [here](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Authentication.Token/TokenAuthentication.cs#L83) should probably be wrapped in a try/catch, though.

**Comment by delaneyj** [comment]
Yeah I would think this would wrap and send the proper status code.  I'm new to Nancy and just getting started so do I need to make a pull request or is this enough info for the proper devs?  

Going to make a couchbase auth token scheme anyways so not blocked by this but was just using as reference.
