### ISSUE TITLE
How to register routes at runtime?

### ISSUE THREAD

**Issue by jgillich** [NancyFx/Nancy#1798]
I'd like to not use static modules, but rather add routes programmatically at runtime (prior to calling `NancyHost.Start()`). Searching didn't return much, any pointers? Thanks!

**Comment by BalassaMarton** [comment]
I have the same problem. Consider this module:
```cs
    public class MyModule : NancyModule
    {
        private static bool _pluginInstalled = false;

        public IndexModule()
        {
            Get["/install"] = _ =>
            {
                _pluginInstalled = true;
                return "Plugin installed";
            };

            if (_pluginInstalled)
                Get["/plugin"] = _ => "<h1>Plugin working</h1>";
        }
    }
```
Expected behavior would be (without any knowledge of the inner workings of Nancy) that when I open the `/plugin` page after opening `/install` I get a response other than the actual 404.
Seems like Nancy is registering routes only when `NancyHost.Start()` is called.

**Comment by jgillich** [comment]
@BalassaMarton That can't possibly work because at the time the constructor is called, `_pluginInstalled` is always `false`. You might want to try the following:

```
Get["/plugin"] = _ => {
    if(_pluginInstalled) {
        return "<h1>Plugin working</h1>";
    } else {
        return 404;
    }
}
```

But that's not really related to what I meant. I don't even have a module, I'd rather do this (pseudo-code):
    
    Nancy.Routes.Get['/foo'] = (_) => "foo";

**Comment by BalassaMarton** [comment]
Nope, `_pluginInstalled` is a static field, so after executing the `/install` route, it will be `true` next time the constructor is called, but the route is not recognised.

**Comment by thecodejunkie** [comment]
To make this work you would have to do a bit of re-plumbing of Nancy. The reason is that, because of performance reasons, all routes are registered once - during the startup of the application. This build the route cache and also helps propulate the routing trie (the thing that figures out, with lightning speed, which route to invoke). So if you added routes at runtime you would have to rejigg them so they are refreshed somehow (no capability in them for that at this time).

Optionally you could look at implementing your own `INancyModule` and returning your own route collection (we don't really care how it's populated), or look into implementing a new `IRouteCache` that not only looks at INancyModule instances, to get an additional `IEnumerable<Route>` (https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Routing/Route.cs) from another place that's not INancyModule (in effect, creating a form of aggregate route cache builder)

**Comment by jgillich** [comment]
@thecodejunkie Just to be clear, even if I would implement my own `INancyModule`, there is still no way to add routes at runtime, because they would be registered at startup, right?
And when you say at startup, do you literally mean application startup or when `NancyHost.Start()` gets called?

**Comment by thecodejunkie** [comment]
Well, if you want to register a route - at any given time during the lifetime of your application, then no it would not work to register a route because of the route cache / trie that I mentioned.

Startup = the first time a request comes in and the bootstrapper runs for the first time

What is is that you are trying to achieve?

**Comment by felipeleusin** [comment]
This seems like something that should be handled by a Before Hook. You can flag the modules you wan't  disabled with an extension method like this.DisableUntilInstallation() that basically returns 404 while a static IsInstalled is set to false.

**Comment by jgillich** [comment]
@thecodejunkie Oops, somehow I didn't get a notification for your reply.

I'm working on a little framework that abstracts resources away from the underlying transport mechanism (HTTP in the case of Nancy, but could also be WebSockets/XMPP/whatever). Resources are just model classes that you can perform CRUD methods on.

The part that interacts with Nancy receives the models and should then register the routes for each model (like `GET /foo`, `GET /foo/{id}` etc). This is where I'm having trouble; the models are passed to my framework during the setup phase so I can't use static NancyModules.

If that isn't clear enough, here is how this would look in code:
```C#
void Program()
{
    var fx = new MyFramework();
    fx.RegisterResource(MyModel);
    fx.RegisterProvider(new NancyProvider());
    fx.Listen();
}

class MyModel : Model
{
    public string Name = "MyModel";
}

class NancyProvider()
{
    void RegisterResource(Model model)
    {
         string route = String.Format("/{0}", model.Name);
         nancyHost.Routes.Get[route] = (_)  => { return GetAll() }
         nancyHost.Routes.Post[route] = (_)  => { return Insert(_.model) }
    }
}
```

**Comment by wildshane** [comment]
Hi @jgillich did you ever get this to work for you?

I am currently helping investigate a similar approach by which it would allow for a controlled set of model properties to define routes for the purpose of query filtering.
Plan would be to wire into a LINQ syntax to retrieve the required data set.
I could imagine this would wreak havoc on any form of API documentation (eg swagger) though.

**Comment by jgillich** [comment]
@wildshane I don't remember and don't have access to the code anymore, sorry!
