### ISSUE TITLE
Adding additional items to token.

### ISSUE THREAD

**Issue by leojh** [NancyFx/Nancy#1817]
I've noticed that one can add additional item to token validation through the TokenConfiguration AdditionalItems property. However, adding items to token to be pulled out later is not supported out of the box.
Is this behavior by design?

**Comment by jeffdoolittle** [comment]
@jessetechie ping

**Comment by divmgl** [comment]
I just took a look at `Tokenizer.cs` and it looks this is default behavior. It will only tokenize username, claims and date. 

Normally this would be fine for me, but I'm working on a coworker's app who is using token authentication *to retrieve additional properties from a data store*. /facepalm

Not sure how I'm going to manage storing additional items in the token to be retrieved later.

**Comment by jessetechie** [comment]
The purpose of the AdditionalItems property is to provide an extensible way to ensure that the client sending the token is the same client that got the token.

As you can see from [Tokenizer.cs Line 30](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Authentication.Token/Tokenizer.cs#L30), the User Agent string from the request header is automatically added to the collection as an example of the minimum you'd want to do.

Then at [Line 122](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Authentication.Token/Tokenizer.cs#L122) the token value is simply checked for equality with the configured ```Func<NancyContext, string>```.  Basically this allows you to use something like [FingerprintJS](https://github.com/Valve/fingerprintjs) for web clients, or a device id for mobile clients, and sending those values in the request header when first requesting the token and for every subsequent request.

The purpose of Nancy.Authentication.Token is to turn a token string into an IUserIdentity that Nancy can use.  Using the token document for reasons other than that doesn't really fit with the design.  

I'm curious what kind of data would need to be pulled out of the token and used by the application, especially since the client can't modify the token due to the hash, so the data you'd be pulling out would be coming from the server in the first place.  If there's a need to have the client send data as part of some kind of stateless session variable, well, that's what cookies are for, right? :)  You can still use cookies for other things, you just don't need to use them for authentication when you use Token Auth.

Hope that helps!

**Comment by divmgl** [comment]
@jessetechie thanks for reaching out. I am going to show my coworker your response.
