### ISSUE TITLE
NancyFX failed TechEmpower benchmarks

### ISSUE THREAD

**Issue by webcoyote** [NancyFx/Nancy#1904]
I'm happily using NancyFX for dashboards because it makes it easy to instrument servers without much code, but I felt it important to point out its poor showing in the recent TechEmpower benchmark results.

NancyFX hasn't performed well in the [benchmark](https://www.techempower.com/benchmarks/#section=data-r10). It runs ~1/1000th the speed of the top test (both Windows and Linux), and in fact every other language has frameworks that run substantially faster -- even non-compiled languages like Ruby and Python.

If you'd like NancyFX to gain greater adoption it would be a good idea to look into why it compares so poorly with other frameworks, both on Windows and Linux. (Note: Windows benchmarks can be found on round 9; they weren't run for round 10).

**Comment by khellang** [comment]
What benchmarks are you most concerned about? The JSON serialization? What other frameworks are you comparing it to? My bet is that most of the overhead comes with ASP.NET and Mono's (rather poor) implementation of it.

**Comment by grumpydev** [comment]
If someone wants to take this one that's fine, but we didn't submit Nancy to it and I don't think we'll be looking at it directly - "generic" benchmarks like that are of little value, and the results are so obviously wrong that what little value it gives has to be taken with a large pinch of salt.

Nancy itself has been benchmarked and stress tested to some pretty crazy extremes (millions of requests and millions of routes/modules) and we are happy with both the performance of it, and how it compares to other frameworks (favourably in most cases, with only service stack generally being faster, but that's understandable given the limitations of its routing at the time) - that, along with people doing actual perf testing for their actual requirements are far more important imo than that weird web framework willy waving contest :)

**Comment by webcoyote** [comment]
@grumpydev: Successful projects have strong communities. Communities grow because folks discover compelling reasons to join. On Hacker News the TechEmpower web benchmark has gained more mind-share than any similar project because it is credible in its benchmarking goals and exceptionally broad in its testing. If folks review the results of that benchmark they'll come away with a poor opinion of .NET and NancyFX (if they even bother to read that far down the list), and they're unlikely to join this community.

I can understand that you might not wanting to put the effort into discovering what the problem is, but discouraging others from doing the same by discounting the results as "willy waving" is not a particularly constructive response.

For someone with extensive knowledge of NancyFX it might be as simple as changing some configuration files, but if you're going to wave everyone off I guess we won't ever know.

**Comment by webcoyote** [comment]
@khellang: If you look at round nine of the TechEmpower tests (sorry -- can't direct link to the page on the site) you'll see Windows (.NET) is also included, and it has a similarly poor showing, so the poor benchmarking results are not just a mono issue.

**Comment by khellang** [comment]
@webcoyote FWIW I submitted a PR to the repo with some changes that (hopefully) will speed things up a bit. My main concern is that the whole thing is hosted on top of ASP.NET, which still hasn't been addressed. It would probably score higher if it was hosted directly on top of IIS/nginx with OWIN, but I don't have enough knowledge on how things are set up to make those adjustments right now. See https://github.com/TechEmpower/FrameworkBenchmarks/pull/1565 for reference.

**Comment by hamiltont** [comment]
Hi, I'm from the frameworkbenchmarks project and can add some context. Currently our windows support is really poor - [quoting the blog post techempower released with R10](https://www.techempower.com/blog/2015/04/21/framework-benchmarks-round-10/): 

> Windows support has again fallen behind. We have received a great deal of Windows help in the past, but we don't have the internal capacity to keep it current with the evolution of the project. Round 10 does not include Windows tests, but we'd very much welcome any help catching Windows up for the next round.

which hits the nail on the head - there were about 10 commits / day over the course of a year including massive changes to the toolset, and the TFB team frankly didn't have the experience or manpower to support windows properly. One of the main goals for R11 is to bring windows support back, feel free to [comment on any of these github issues or send PRs](https://github.com/TechEmpower/FrameworkBenchmarks/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Windows+Compatibility%22)

We've worked quite hard to keep mono working, so we can at least easily let our continuous integration system verify if changes to C# codebases check out (e.g. check out the bottom of [this screen](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/59735617) where our CI has tested @khellang's PR), but we are well aware that mono support isn't comparable to native windows support. 

For those unaware with our setup, each framework can define multiple configurations in the [benchmark_config.json](https://github.com/khellang/FrameworkBenchmarks/blob/nancy-updates/frameworks/CSharp/nancy/benchmark_config.json). If you compare that with the Travis-CI hyperlink above, you'll note that only the configurations dependent on Linux were automatically tested. 

So that's the context, hope it helps. Any participation from windows-experienced folks is very very welcome. The highest-priority item is [this issue on setting up continuous integration for windows](https://github.com/TechEmpower/FrameworkBenchmarks/issues/1038) to help us test incoming windows-dependant PRs
