### ISSUE TITLE
Issue with TextResponse

### ISSUE THREAD

**Issue by JustinSarwer** [NancyFx/Nancy#1914]
I'm trying to use the nancy TextResponses for a RESTful API, powered using nginx 1.6.3, and I found an issue when trying to return a TextResponse without "contents" and only giving it a status code as a parameter, which ends up ALWAYS responding with 502 Bad Gateway.

This issue is solved simply by passing in a string to the contents of the TextResponse, but why should it always return 502 without a contents string? Did I miss something in the documentation?

Thanks,
Justin

**Comment by khellang** [comment]
That sounds very weird. What happens if you omit the `contents` parameters from the constructor, is that the `Contents` property won't be touched, and it'll use what the base class (`Response`) sets, which is an [empty delegate](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Response.cs#L30). It sounds like the host you're using doesn't handle empty streams very well.

**Comment by khellang** [comment]
Have you tried checking the Nginx log file located in `/var/log/nginx/`? It should contain the reason why you get the 502.
