### ISSUE TITLE
Convert the old IHideObjectMembers to the new IFluentInterface

### ISSUE THREAD

**Issue by kzu** [NancyFx/Nancy#1921]
Plz switch to the recommended content nuget package: http://www.nuget.org/packages/IFluentInterface

Much appreciated!

**Comment by grumpydev** [comment]
Why? All that seems to do is include a file that does exactly the same thing but adds another (albeit dev only) dependency?

**Comment by phillip-haydon** [comment]
This doesn't add anything but a dependency. 

Closing this but will reopen if you can provide there is real value to this.

**Comment by damianh** [comment]
I do like source packages, but something of this size that's just an interface is of questionable value </opinion>

**Comment by kzu** [comment]
Many other projects are using this nuget now, which again, introduces NO
runtime dependency and serves the purpose of increasing the awareness to
the package and its usefulness.

If you found my little interface useful, I'd politely ask why NOT use this
*zero impact* nuget instead? Doesn't seem to me that there's much to lose
either by doing so...

**Comment by khellang** [comment]
There's nothing to win, and nothing to lose - who wants to send the PR? :stuck_out_tongue_closed_eyes:

**Comment by thecodejunkie** [comment]
That's not true. The interface is renamed from `IHideObjectMembers` to `IFluentInterface` so it would be a breaking change for all that take a dependency on Nancy.dll and use that interface. I know for a fact that there are (Nancy) community extensions that make use of the interface. Not to mention that we use it on in a lot of our own packages, which would mean that all of those packages would have to be updated as well. Yes, you could argue that you can do something like

```c#
public interface IHideObjectMembers : IFluentInterface
{
}
```

And slap an `ObsoleteAttribute` on it, but I am still struggling to see any value other than "just because", especially when you factor in all the work that would need to be done on our various project + community projects (or maintain a shim interface for a period of time).

Had this been a new project then I'd be more prone on doing it, but seeing as we've used this for 4+ years now... not as much
