### ISSUE TITLE
Debugger-friendly Context

### ISSUE THREAD

**Issue by hmemcpy** [NancyFx/Nancy#1950]
Right now, when exploring the Context object under the debugger, it doesn't immediately show much information:
![image](https://cloud.githubusercontent.com/assets/601206/7935249/160c3648-0938-11e5-9d6f-466c4d2cc992.png)

I propose adding various `[DebuggerDisplay]` annotations on core Nancy classes, so they can expose useful information immediately, without having to drill down.
Does that sound like a good idea?

**Comment by khellang** [comment]
Absolutely! Want to pitch a suggestion?

**Comment by NTiering** [comment]
as a newbie would it be possible for me to grab this one / if so , how ? (I've never contributed to an OS project before)

**Comment by khellang** [comment]
@NTiering Yeah. This is a perfect "beginner" task :smile: [CONTRIBUTING.md](https://github.com/NancyFx/Nancy/blob/master/CONTRIBUTING.md) should cover the information you need to get started.

Since this is a pretty "open" issue, it would be cool if you just jumped on it and came up with a sensible suggestion (preferably through a pull request, so it's easier to discuss), and then we can take it from there.

If you have other questions, just ask :wink:

**Comment by NTiering** [comment]
Cheers. Will do

**Comment by thecodejunkie** [comment]
@NTiering @hmemcpy did either of you ever get anywhere with this?

**Comment by thecodejunkie** [comment]
@hmemcpy what, exactly, did you have in mind? Looking at it, there's not a lot of things we could lift up. Maybe a bit about the request (path, method, schema, port) and that's about it?

**Comment by felipeleusin** [comment]
From looking here I would make ModelValidationResult show IsValid and maybe DynamicDictionary get a JSON notation? So things like parameters show like { userId = "fooo" }
