### ISSUE TITLE
Subfolders skew Content path

### ISSUE THREAD

**Issue by bluebaroncanada** [NancyFx/Nancy#1955]
If I put a view in a sub folder, I can't access the /Content directory.
i.e. <script src="~/Content/...

**Comment by thecodejunkie** [comment]
@bluebaroncanada using what view engine? Could you give a short folder structure sample that we could use to reproduce this? Thanks

**Comment by thecodejunkie** [comment]
Going to close this for now because I cannot reproduce it

If you are using the Razor view engine, then you should use `@Url.Content("~/......")` for content paths and if you are using SSVE then the equivalent is `@Path['~/....']`

Should this still be an issue for you, please comment and re-open the issue.

Thank you
