### ISSUE TITLE
Docs: add end-to-end examples in all areas that cover the basics

### ISSUE THREAD

**Issue by Aaronontheweb** [NancyFx/Nancy#1994]
Based on the lively discussion we had on Twitter about the state of Nancy's docs, @khellang suggested that I edit the Wiki and create an issue for how to make basic things obvious to beginners.

So I added the following: https://github.com/NancyFx/Nancy/wiki/Model-binding#a-complete-model-binding-example

What made it hard for me to pick up Nancy was the lack of end-to-end examples. People have different learning styles, and mine is reverse-engineering from examples. Kinesthetic learning. Right now the docs go into a lot of detail on how things work, but they don't actually show complete examples of the things they describe working.

Here are the areas where I think this would be really helpful:
- Modeling binding (which I tried to do here:https://github.com/NancyFx/Nancy/wiki/Model-binding#a-complete-model-binding-example)
- Razor views with models
- Razor template composition (_viewstart, partials, RenderSection, etc...) - there's small differences between ASP.NET MVC and Nancy such as `<link href="~/content/bootstrap.css" rel="Stylesheet" />` instead of `@Styles.Render("~/Content/bootstrap.css")` and `@Html.Partial("Views/Shared/_scripts.cshtml")` instead of `@Html.Partial("~/Views/Shared/_scripts.cshtml")`... Piecing all of that together from examples, third party blog posts, and querying stack overflow took me a long time.
- Forms authentication (put all of the pieces together into a complete picture, like how this link in the footer did http://www.philliphaydon.com/2012/12/forms-authentication-with-nancyfx/)
- Dependency injection (even if this is handled through third party modules, have a section on it.)

**Comment by 06b** [comment]
I know that I've tripped over the ~/ difference with @Html.Partial and that has appeared a few times within the github issues like issue #1738 for example. When I found the [Nancy from an MVC Dev POV](http://www.endycahyono.com/article/nancy-from-mvc-dev/) blog post it was helpful to me since I was coming from a dev shop that was only mvc.

+1 on the Complete Picture example you added, it does help give a good overview. A suggestion would be to perhaps also add a link to a stand alone repo so someone new to nancy could also download it and run the code, see how it works, etc. I guess an example would be how someone did for the Blog Posts, Videos&Audio section on [error handling](https://github.com/NancyFx/Nancy/wiki/Blog-Posts%2C-Video-%26-Audio#error-handling)

**Comment by janus007** [comment]
Couldn't agree more, NancyFX is a truly master piece, but takes tremendous focus to get started with.

**Comment by thecodejunkie** [comment]
Cool. Let's roll with this.. what would be a good (other than what @Aaronontheweb mentioned) "Beginners story"? Thought we had one, but clearly not one that works for everyone =)

**Comment by phillip-haydon** [comment]
@thecodejunkie I think there's 2. 

1) Creating your first Web Application with Nancy hosted with OWIN
2) Creating your first self-hosted Application with Nancy hosted with OWIN

Mostly because I see people getting confused between the two in JabbR. But also I think we should slowly begin moving away from the non-owin self-host, and asp.net host. Also, the WCF Host needs to be burned at the stake. 

These are just `setup and return hello from Nancy` apps.

**Comment by phillip-haydon** [comment]
![image](https://cloud.githubusercontent.com/assets/895629/9102306/27958f04-3c23-11e5-8fd3-ac0abcef4e5e.png)

**Comment by stefansedich** [comment]
+1 here for me one I can think of off hand that I fought recently would be a "getting started with DataAnnotations Validation" especially when it comes to needing things like validation adapters and how to wire everything together.

**Comment by jchannon** [comment]
We also have sample.nancyfx.org, bit out of date as well as https://github.com/NancyFx/DinnerParty which may have helped @Aaronontheweb

**Comment by khellang** [comment]
And not to forget http://blog.nancyfx.org/ and https://github.com/NancyFx/Nancy/wiki/Blog-Posts%2C-Video-%26-Audio :)

**Comment by jjchiw** [comment]
I have the typical TodoMvc with Nancy https://github.com/jjchiw/NancyRavenTodoMvc :) I should update to 1.2.0. I think that the documentation that exists (wiki, tutorial, blogs, google group, jabbr) are good to start. 
I also have this https://github.com/jjchiw/rpsls (I should update it too - http://rpsls.apphb.com/)

**Comment by khellang** [comment]
Just got another example where this would might've helped; #1998 :smile:
