### ISSUE TITLE
Docs: unified OWIN auth for Nancy + SignalR

### ISSUE THREAD

**Issue by Aaronontheweb** [NancyFx/Nancy#1995]
I found this but wasn't able to get it to work in my own project
https://github.com/damianh/NancySignalrOwin

IMHO, this is a killer feature that distinguishes Nancy from ASP.NET MVC - a straightforward way of using the OWIN middleware to accomplish unified authentication and authorization for both websockets and web.

If you could do a tutorial or walkthrough explaining how to do this, that'd be a life-changing feature for me.

**Comment by thecodejunkie** [comment]
Ping @damianh

**Comment by felipeleusin** [comment]
I'm pretty sure you can use some auth middleware before both SignalR and Nancy and in Nancy use https://github.com/NancyFx/Nancy.MSOwinSecurity for handling the security and I think SignalR just works with Owin auth.

**Comment by damianh** [comment]
`Nancy.MSOwinSecurity` provides integration with `Microsoft.Owin,Security`. Specifically, it gives you access to `IAuthenticationManger`. It also allows you to use `ClaimsPrincipal` instead of Nancy's `IUser` (Nancy v2 will use `ClaimsPrincipal` and drop `IUser`). The [readme](https://github.com/NancyFx/Nancy.MSOwinSecurity#how-to-use) has example of usage.

As @felipeleusin, signalr will just consume the owin key "server.User" as is.

@Aaronontheweb I'll take a look at that repository.

**Comment by psibernetic** [comment]
Props for moving to ClaimsPrincipal.
