### ISSUE TITLE
Replace the internal json serializer with SimpleJson

### ISSUE THREAD

**Issue by thecodejunkie** [NancyFx/Nancy#2061]
- [ ] Switch out JSON Serialization for SimpleJson
- [ ] Update contract and ensure dynamic binding works

**Comment by ravensorb** [comment]
As a suggestion what about replacing the internal serializer with a contract for serialization and then allow us to register which every serializer we want to use (SimpleJson, Json.NET, etc)?

**Comment by phillip-haydon** [comment]
@ravensorb we already have a contract for that, which allows us to have Nancy.Serialization.JsonNet

https://www.nuget.org/packages/Nancy.Serialization.JsonNet/

The problem is we currently use the implementation from Mono to do serialization, which has numerous bugs in it. So the plan is to replace it with SimpleJson as the default.

**Comment by felipeleusin** [comment]
Is this up for grabs?

**Comment by phillip-haydon** [comment]
@felipeleusin we welcome any and all contributions to making Nancy even more awesome. There's absolutely no reason why you can't contribute this. So feel free :)

Just needs to pass @thecodejunkie's very very strict coding standards. :)

**Comment by phillip-haydon** [comment]
Also @thecodejunkie to confirm we are going ahead with SimpleJson?

**Comment by grumpydev** [comment]
This is more complicated than it sounds though because it includes changing the serialiser contract, and how the binding works, to allow for dyamic model binding.

Still up for grabs, but it's more than just "replace x with y", although that is a reasonable start in itself.

**Comment by phillip-haydon** [comment]
@grumpydev changing to SimpleJson should open way to fix the dynamic model binding stuff right? 

So if iteration one was getting the replacement in there, then the next iteration amending the contract and the this.Bind<T> stuff etc. We can have smaller pieces. 

I'm just thinking, getting the replacement in and ensuring nothing breaks before we fix the other things.

**Comment by grumpydev** [comment]
I think that's pretty much what I said? :) just don't want to to be forgotten that there's more work than just switching it out.

**Comment by phillip-haydon** [comment]
We have checkboxes on the originally issue now :) feel free to amend them accordingly.

**Comment by felipeleusin** [comment]
Ok. I'll take this first step and we'll see where it goes.

**Comment by thecodejunkie** [comment]
Yes, I have confirmed with @prabirshrestha that it is OK for us to embed it and even strip out platform support for everything we don't need (.NET 4.0 and below).

He did warn us that we do have to keep an eye out for infinite recursions because it does not do a very good job guarding that. We currently allow you to control this with `JsonConfiguration.MaxRecursions` in the existing code

**Comment by jasonmead** [comment]
So I gave this a shot this weekend:

https://github.com/jasonmead/Nancy/tree/SimpleJsonSpike

I had a few goals:
- Limit the changes to SimpleJson.cs to allow for easier upgrading to future versions
- Limit the changes to the Nancy.Json namespace so it didn't spider all over the place.

I made it most of the way, but ran into a few issues. Most of them are related to the differences between how SimpleJson works and how the existing json classes work.
- SimpleJson does not handle circular dependencies. So one of the unit tests is now hitting a StackOverflowException
- SimpleJson escapes \ characters so the WCF DateTime serializations are broken
- SimpleJson does not have the concept of recursion depth
- SimpleJson implements reflection caching in the PocoSerializationStrategy. Because the JsonBodyDeserializer creates a new one on every request, we lose the caching.

Most of these issues can be solved by changing how SimpleJson works but I did not want to go down that path without getting some feedback first.

**Comment by thecodejunkie** [comment]
@jasonmead can you send it as a PR? Easier to review since we can leave comments on it

**Comment by jasonmead** [comment]
Done. Please note that this is definitely not complete.

https://github.com/NancyFx/Nancy/pull/2163

**Comment by jasonmead** [comment]
Any suggestions or comments on how to continue?

**Comment by khellang** [comment]
Commented on the PR.

**Comment by phillip-haydon** [comment]
@jasonmead 

In regard to your 4 points

1. Don't care about circular dependencies, anyone running into that issue are doing it wrong. People run into that returning EF models directly.
2. We have no care for WCF so we can rip that crap out and support the dates properly.
3. Again like circular dependencies, recursion depth isn't our responsibility, people should return small concise models.
4. This is the only concern, but this should be relatively easy to fix with a static cache or something along those lines.

**Comment by jasonmead** [comment]
Thanks @phillip-haydon and @khellang. That's exactly the guidance I was looking for. I'll get the pull request updated today or tomorrow.

As far as the tests testing the first 3 items you don't care about, do you want me to remove them or marked them as ignored?

**Comment by phillip-haydon** [comment]
Yes we don't care about them, atleast for now. If people want that control they can use json.net for more fine grain control.

Only 4 is an issue for performance and I think that is solvable.

**Comment by jchannon** [comment]
@jasonmead any update to this or the PR

**Comment by jchannon** [comment]
See #2313
