### ISSUE TITLE
System.MissingMethodException when running Nancy with Mono

### ISSUE THREAD

**Issue by Infernno** [NancyFx/Nancy#2064]
Hello guys.
I have a small problem when running Nancy with **Mono** under Windows & Linux.
The application fails to start due to **MissingMethodException**. This happens when you are trying to define the conventions in the bootstrapper. 

This is how it looks:
![Error](https://cloud.githubusercontent.com/assets/7915327/10107471/896c26ea-63e5-11e5-9292-9dc527a73a92.PNG)

In anyway, simple repro project is [here](https://github.com/Infernno/NancyBug/tree/master/ConsoleApplication2).

P.S. Google said that the problem might be in IoC container, more specifically - ```Array.Empty``` is passed as default parameter in ```Expression.Call``` method, but ```Array.Empty``` isn't implemented in Mono, so we get an exception.
P.S.S. Reproducible under Windows or Linux with latest Nancy (1.3) and Mono (4.0.4). Not reproducible with .NET Framework 4.6.

**Comment by khellang** [comment]
I'm not sure what's happening here. Nancy is built against .NET 4.0, which doesn't have `Array.Empty`. That's an API that was added in .NET 4.6.

**Comment by thecodejunkie** [comment]
Hi,

The short version is; this is not a bug in Nancy, it's a run-time framework / compiler issue. The `StaticContentConventionBuilder.AddDirectory` takes an optional parameter `params string[] allowedExtensions` and it's the `string[]` that is being handled incorrectly for some reason. To be honest I've not looked too deep into this, but if you search for [array.empty missingmethodexception](https://www.google.se/?gfe_rd=cr&ei=56EFVoiGOo-r8we4iqXQCQ&gws_rd=ssl#q=array.empty+missingmethodexception) you see that there are lots of people experiencing this, in different scenarios and different tech stacks

This is what I think you're doing.

1. You are compiling your application on .NET Framework 4.6 where the absence of values to a `params string[]` parameter gets compiled into `Array.Empty<T>()` by Roslyn.
2. You then attempt to run this compiled application on an early build of .NET Framework or Mono, where `Array.Empty<T>` does not exist ([source](https://msdn.microsoft.com/en-us/library/dn906179(v=vs.110).aspx) notice that it says _Available since 4.6_)

The way to work around this is to not target .NET 4.6, but instead target .NET 4.5.x

**Comment by khellang** [comment]
This might actually be a compiler optimization. I guess when you call a `params T[]` method with no arguments, the compiler will generate a call using `Array.Empty<T>` in order to avoid any allocation.

**Comment by cloudhunter89** [comment]
What certain of Nancy are you using.

**Comment by cloudhunter89** [comment]
Sorry.  What version of Nancy are you using?

**Comment by MahendranShanmugam** [comment]
Hi,

I am Nancy 1.4.4 version and also where we get the Nancy 2.0.0-clinteastwood can you please suggest me.

Thanks,
Mahendran S.

**Comment by MahendranShanmugam** [comment]
Hi,

We have report application so we like to rendering our report using Nancy web API how to do. Can you please explain.

Regards,
Mahendran S.
