### ISSUE TITLE
use Func return as Task instead of Task<dynamic> in RouteBuilder

### ISSUE THREAD

**Issue by composite** [NancyFx/Nancy#2107]
sorry for my poor english.

I make Nancy Attribute-Driven Module. (https://gist.github.com/composite/aac8858a04afe7a222f8)
I think Nancy is simple if normal routing usage like:
```cs
public MyModule(){
    Get["/", true] = async (d,e) => "Hello World";
}
```
but, if use normal method instead of lamda expression... make a method with return type must be `Task<dynamic>`. other type like `Task<string>` will causing exception.
```cs
public MyModule(){
    Get["/", true] = MyGet;
}

 // fine
public async Task<dynamic> MyGet(dynamic a, CancellationToken b) => "Hello World!";
// method is fine but cause exception as "InvalidCaseException : Cannot cast Task<string> to Task<dynamic>.
public async Task<string> MyGet(dynamic a, CancellationToken b) => "Hello World!";
``` 

I suggest that `Routebuilder[string] = ` set type as `Func<dynamic, CancellationToken, Task>` instead of `Func<dynamic, CancellationToken, Task<dynamic>>` for more routing scalability.

**Comment by grumpydev** [comment]
We already have a sample of attribute routing as a demo, although I wouldn't recommend anyone actually use it:

https://github.com/NancyFx/Nancy/tree/master/src/Nancy.Demo.CustomModule

As for just returning Task, this wouldn't work as we require that you return an "object" of some sort for content negotiation, just completing a Task isn't enough - I also don't think we can add this in addition to the current API, as that would just be differing on return type which C# doesn't support.

I'm not sure what the problem is though - either have Task<dynamic> as your return type, or call the method rather than using a method group: Get["/", true] = async (d, e) => MyGet(d, e);
