### ISSUE TITLE
Nancy.Authentication.Token removed?

### ISSUE THREAD

**Issue by thomasbindzau** [NancyFx/Nancy#2109]
I tried to browse the source code for the token authentication, but found that is was removed in the following commit:
https://github.com/NancyFx/Nancy/commit/1fa90ef85c2fa511c65f3e4090e12e6ed54c3af9

A mistake, or has it been moved somewhere else?

**Comment by khellang** [comment]
Yes, it has been removed. You can see the discussion at https://github.com/NancyFx/Nancy/pull/1820#issuecomment-77757113. It's basically because we're moving to ClaimsPrincipal for Nancy v2 and it doesn't quite fit. We also don't really know the code well enough to maintain the code properly, so we usually end up pinging @jeffdoolittle for all kinds of stuff. It would be great if someone in the community would pick it up and maintain it, though :smile:

**Comment by gzpbx** [comment]
removed from Nancy 1.x or 2.x ?

**Comment by khellang** [comment]
Removed from 2.x :smile: If you need tokens, take a look at Katana's JWT support...
