### ISSUE TITLE
route percent sign Erro?

### ISSUE THREAD

**Issue by uliian** [NancyFx/Nancy#2187]
I define a route :
```
Get["Home/{Id}/{UserId}"] = (p) =>  { return p.Id;  };
```

if I request Url:
```
/Home/fdsafdsafdsafadsfdasfdasfadsfadsfdsafadsfdsafdsafdasfdsafdsadf/1111
```
Success

but I request Url:
```
/Home/sl25REVfP9ihAQP%2fhMiB6DVGQC8U4EqXc9Dukr%2bhx5Q%3d/1111
```

response is 404 Not found!

if url exist '%' the program can't route success

**Comment by uliian** [comment]
the application host in asp.net, NancyHttpRequestHandler have  received requet ,the HttpContex auto  '%2f'  Covert to '/' .
Nancy route Invalid

**Comment by jvandertil** [comment]
That's because the % sign is used in URL encoding: https://en.wikipedia.org/wiki/Percent-encoding

So, given your request URI:
```
/Home/sl25REVfP9ihAQP%2fhMiB6DVGQC8U4EqXc9Dukr%2bhx5Q%3d/1111
```
It decodes to:
```
/Home/sl25REVfP9ihAQP/hMiB6DVGQC8U4EqXc9Dukr+hx5Q=/1111
```
Notice the extra '/'.

If you really want to send ``sl25REVfP9ihAQP%2fhMiB6DVGQC8U4EqXc9Dukr%2bhx5Q%3d`` try sending it as ``sl25REVfP9ihAQP%252fhMiB6DVGQC8U4EqXc9Dukr%252bhx5Q%253d``.

At http://meyerweb.com/eric/tools/dencoder/ there is a nice tool you can use to test these things.

**Comment by khellang** [comment]
Yes. As @jvandertil says; this is expected.
