### ISSUE TITLE
Forms authentication: cookie exist, but didn't call GetUserFromIdentifier

### ISSUE THREAD

**Issue by MingYueGuWo** [NancyFx/Nancy#2197]
Hi,
I'm not sure if it's a pipeline question. The forms authentication works fine for me. but when server restart, like deployment. when user access the resources that need authentication and the user has logged in before, it will ask the user login again. I have set a long date expiration cookie. I can see the cookie is there when debugging

protected override void RequestStartup(TinyIoCContainer requestContainer, IPipelines pipelines, NancyContext context)

the _ncfa is in context.Request.Cookies and it has right value. but problem is, the code will not call GetUserFromIdentifier but redirect to the login page directly, (happens when application restart, like recompiling the project)

My question is how i can restore user id from cookie whatever the server restart?

Thanks!

**Comment by czhj** [comment]
use your own CryptographyConfiguration
https://github.com/NancyFx/Nancy/wiki/Forms-Authentication#a-word-on-cryptography

**Comment by grumpydev** [comment]
Sounds like you're not using your own crypto config, this is covered in the "A word on cryptography" in the docs:

https://github.com/NancyFx/Nancy/wiki/Forms-Authentication

For future reference please use Stack Overflow or the Jabbr chat channel for general questions, rather than filing an "issue" - thanks.

**Comment by MingYueGuWo** [comment]
Thanks guys!
