### ISSUE TITLE
Handle request as stream to allow preemptive cancellation of file upload to save bandwidth

### ISSUE THREAD

**Issue by Ralf1108** [NancyFx/Nancy#2339]
Currently I have implemented file upload in nancy fx like that:

Client code:

```
 var testData = new byte[1024 * 1024];
 File.WriteAllBytes("testdata.bin", testData);

 var client = new WebClient();
 var res = client.UploadFile(host + "/upload", "testdata.bin");
```

Server code:

  ```
 public class UploadModule : NancyModule
{
    public UploadModule()
    {
        Post["/upload"] = x =>
        {
            const int userQuota = 10000;

            var file = Request.Files.Single();
            var outFilePath = Path.Combine(Path.GetTempPath(), "out.bin");
            using (var outFile = File.Create(outFilePath))
            {
                var readBytesSum = 0;

                int readBytes;
                var buffer = new byte[8192];
                while ((readBytes = file.Value.Read(buffer, 0, buffer.Length)) != 0)
                {
                    readBytesSum += readBytes;
                    if (readBytesSum > userQuota)
                        throw new InvalidOperationException("Max file size exceeded!");

                    outFile.Write(buffer, 0, readBytes);
                }

                outFile.Flush();
            }

            return HttpStatusCode.OK;
        };
    }
}
```

If a user now uploads a 10 mb file the operation on the server will be canceled after all 10 mb are first recieved and then checked.

I wondered if there is a possibility in Nancy to get the request data as a stream and make a fast fail path if incoming data reaches a defined quota. If quota is reached the connection could be dropped and no further download bandwidth on server will be wasted.

As far as I get to know is that Nancy will always buffer the whole input data either in memory or in temp file. So I think my requirement would need more access to the low level request pipeline?

also on stack overflow: [http://stackoverflow.com/questions/35842479/nancy-handle-request-as-stream-to-allow-preemptive-cancellation-of-file-upload-t](url)

**Comment by 06b** [comment]
So just my two cents here...

If you are wanting to avoid the bandwidth on the server being wasted and since in your case you have client side code so you aren't restricted to a non-javascript solution, couldn't you check the size of the file uploaded on the client side and not upload it if it exceeds the limit? Then the server side code would remain as is so in the event someone is modifying the javascript to bypass the upload limit then the server would still catch it.

**Comment by Ralf1108** [comment]
Could you please explain how the server could detect manipulation of the javascript code?
Also the client code should be possible in arbitrary programmning language and the server should be possible to enforce this cancellation without restriction on the client side.

**Comment by 06b** [comment]
I might have misunderstood your original question but I'll explain what I was thinking to my original response.

With Javascript you could detect the file size somewhat like [this] (http://stackoverflow.com/questions/4112575/client-checking-file-size-using-html5) and if the filesize is greater than the limit you wouldn't bother sending it to the server (so that would avoid the bandwidth usage on the server), else if it's less than the limit then you would send it to the server. 

Since I was using javascript as the example which someone could modify the limit on the client side and then the fall back would be that if the server side code would just enforce the limit like it currently does - so granted it doesn't solve your issue of avoiding the extra bandwidth completely but in theory it might be one method to handle this.

**Comment by Ralf1108** [comment]
ok. thx for the suggestions!
