### ISSUE TITLE
404 Error after ILMerge

### ISSUE THREAD

**Issue by tringler** [NancyFx/Nancy#2386]
Hello,

I have a strange behaviour after merged the Nancy DLLs to my .exe file. The Nancy instance is self-hosting and the sshtml are embedded to the .exe file.

Nancy is working like a charm before I ILMerge the DLLs to .exe - After merging I get a 404 error.

My CustomBootstrapper:

```
        protected override NancyInternalConfiguration InternalConfiguration
        {
            get
            {
                return NancyInternalConfiguration.WithOverrides(OnConfigurationBuilder);
            }
        }

        void OnConfigurationBuilder(NancyInternalConfiguration x)
        {
            x.ViewLocationProvider = typeof(ResourceViewLocationProvider);
        }

        protected override void ConfigureApplicationContainer(TinyIoCContainer container)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            string[] assemblyNames = assembly.GetManifestResourceNames();

            base.ConfigureApplicationContainer(container);
            ResourceViewLocationProvider.RootNamespaces.Add(
              Assembly.GetAssembly(typeof(MainModule)), "FrontEnd.Webinterface.Views");
        }
```

Any ideas for this problem or any approach how to troubleshoot it? Thanks!

**Comment by thecodejunkie** [comment]
We have never really made any conscious design decisions to ensure that Nancy functions well after having being subjected to ILMerged (or other similar tools). The fact that you get a 404 seems to indicate that Nancy is, at least, being hit but that the route resolution fails. My guess is that it is the default module scanning strategy that is causing the problem. You do not say what version of Nancy you are using, so I am going to assume that you are on the `1.x`-releases, not that it matters that much since the concept is the same in `2.0-alpha`

If you have a look at [NancyBootstrapperBase.Modules][1] you can see that Nancy scans for all `INancyModule` with `ScanMode.ExcludeNancy`. When using `ExcludeNancy` all types that are in the Nancy assembly are going to be ignored. The way it does that is by excluding all types that are in the assembly that is identified by `typeof(INancyEngine).Assembly`.  Normally when you run Nancy independently this is not a problem, however when you have merged it into anothe assembly, it will end up being the same assembly as the rest of your code.

I'm guessing you could override the `Modules` property and provider your own filter, or just explicitly list the names of your modules in there and it should be able to work

Hope this helps!

[1]:https://github.com/NancyFx/Nancy/blob/1.x-WorkingBranch/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L105

**Comment by tringler** [comment]
Thanks for your support! I did it like this:
```
        protected override IEnumerable<ModuleRegistration> Modules
        {
            get
            {
                return
                        
                    AppDomainAssemblyTypeScanner
                        .TypesOf<INancyModule>(ScanMode.ExcludeNancy)
                        .NotOfType<DiagnosticModule>()
                        .Select(t => new ModuleRegistration(t))
                        .ToArray();
            }
        }
```
