### ISSUE TITLE
TinyIoC - Cannot resolve IEnumerable<> when registering on-by-one

### ISSUE THREAD

**Issue by tpluscode** [NancyFx/Nancy#2387]
This seems to be a problem exclusive to TinyIoC within Nancy. When types are registered separately in the `Registrations` class, and auto-registration is disabled, then they aren't injected as multiple

``` c#
public class Registrations : Nancy.Bootstrapper.Registrations
{
    public Registrations()
    {
        Register<IDepRegisteredOnByOne>(typeof(Impl1));
        Register<IDepRegisteredOnByOne>(typeof(Impl2));
    }
}

public class Bootstrapper : DefaultNancyBootstrapper
{
    protected override void ConfigureApplicationContainer(TinyIoCContainer container)
    {
        // disable auto-registration
    }
}

public class TestModule : NancyModule
{
    public TestModule(IEnumerable<IDepRegisteredOnByOne> allDeps)
    {
        // allDeps will be an empty collection
    }
}
```

Seems to work fine with other containers (I tried Windsor and Ninject)

**Comment by grumpydev** [comment]
Correct,  that's what CollectionRegistrations is for (or RegisterMultiple with tinyioc directly)

**Comment by tpluscode** [comment]
Thanks for answering, though I'd ask to reconsider before closing so hastily :wink:.

For one, this behaviour is inconsistent between containers for a moment. Is this a design feature of TinyIoC alone or how it is used inside Nancy?

I personally find this unexpected. If I wanted to register one implementation as singleton and another as per-request, will not be possible with `Registrations`+TinyIoC? Not even if registered directly with the container in `ConfigureApplicationContainer` and `ConfigureRequestContainer` methds?

**Comment by thecodejunkie** [comment]
@tpluscode there is no unified API or standards for these sorts of things in the container world. Nancy provides it's own types (Type/CollectionRegistrations etc) and let the various `Nancy.Bootstrappers.*` implementations make use of them as they deem fit.

You can simply use another overload to get the expected behavior https://github.com/NancyFx/Nancy/blob/1.x-WorkingBranch/src/Nancy/Bootstrapper/Registrations.cs#L77 you have to remember that `Nancy.Bootstrapper.Registrations` is an abstraction (and a simplification/generalization) and not a silver bullet. Using `ConfigureApplicationContainer` and `ConfigureRequestContainer` you gain direct access to the underlying container and are able to make use of what ever features and APIs that it provides

**Comment by tpluscode** [comment]
Too bad. I was hoping that the abstraction, which `Registrations` are would unify the container behaviour to the extent of the API it provides. 

This is especially useful for providers of extension packages. I'm writing one and I hoped that by creating a registrations class it should "just work" with minimal effort on the consumer's part. Currently I understand that some containers would need additional setup code. I agree that containers are not made equal but IMO there is room for improvement

**Comment by tpluscode** [comment]
Then again, your suggestion works of course and calling `Register<T>(IEnumerable)` does the trick. 

I looked but couldn't find a wiki page for `Registrations`. Is there one? If not would you mind me creating one?

**Comment by jchannon** [comment]
If there isn't feel free to create it and let us know... :)

**Comment by khellang** [comment]
> I'm writing one and I hoped that by creating a registrations class it should "just work" with minimal effort on the consumer's part.

This is the exact scenario the registrations concept enables, and it works really well for all kinds of existing "plugins". The Nancy.Swagger registrations is one example of this (see [this](https://github.com/khellang/Nancy.Swagger/blob/master/src/Nancy.Swagger/SwaggerRegistrations.cs#L11)); you just drop in the package, and it Just Works™.

> Currently I understand that some containers would need additional setup code.

What's this setup code? It all depends on your plugin. A plugin could easily handle container setup through the registration hooks. Other configuration might need user input, which is hard to do automatically :stuck_out_tongue: 

> I agree that containers are not made equal but IMO there is room for improvement

If you have any concrete suggestions, we'd :heart: to hear them.

**Comment by tpluscode** [comment]
@khellang I've done some experimenting with cases which I found troublesome. That there are some inconsistencies between various containers. I've gathered the results in [this repository](https://github.com/tpluscode/Nancy.Boostrapper.Experiments)

Ideally I would love to see the exact same behaviour in all bootstrappers. It should be achievable with each container. Otherwise the `Registrations` class has limited use if it gives varying results depending on the bootstrapper

**Comment by khellang** [comment]
@tpluscode Woah, that's some nice work :smile:

> TinyIoC resolves collections only if registered with `RegisterAll`/`RegisterMultiple`

This is exactly what `RegisterAll`/`RegisterMultiple` is for. Several container have explicit multi-registration, like TinyIoC's `RegisterMultiple` method. This is exactly why we differentiate between multiple, "single type registrations" and a single "multi-registration". The only way you can ensure that the user will be able to inject `IEnumerable<T>` across containers is to use `RegisterAll`/`RegisterMultiple`.

Almost all of the Nancy-maintained bootstrappers, like Autofac, StructureMap, Ninject and Windsor are OK, according to your checks. The ones having issues, are, ironically, TinyIoC (related to auto-registration) and Unity.

A lot of the other issues are basically because of Nancy's assumption that you can create a container and append to it later, or just simply a bad implementation of the bootstrapper. We have been experimenting with a new bootstrapper concept for an upcoming version of Nancy. I think this abstraction would get rid of most of these errors by simply configuring everything up-front before building the container, instead of creating it first and adding to it. If you'd like, you can check it out at [khellang/nancy-bootstrapper-prototype](https://github.com/khellang/nancy-bootstrapper-prototype/)

**Comment by grumpydev** [comment]
Not sure about that because the "fixes" are currently because it doesn't support a boatload of stuff we probably need to support :)
