### ISSUE TITLE
Should ConfigureAwait(false) be called in NancyHost?

### ISSUE THREAD

**Issue by xt0rted** [NancyFx/Nancy#2471]
While looking through the code and using the ReSharper [ConfigureAwait Checker](https://github.com/aelij/ConfigureAwaitChecker/) plugin I came across [Nancy.Hosting.Self/NancyHost.cs#L133-134](https://github.com/NancyFx/Nancy/blob/bc44cd30d58ce1b6c7930452304d187248038e18/src/Nancy.Hosting.Self/NancyHost.cs#L133-134).

Should line 133 and/or 134 call `.ConfigureAwait(false)`? The other warning I'm getting is on line 134 because it's not awaited but I wasn't sure if that should be or not.

Those are the only two spots outside of the test projects that don't call ConfigureAwait.

**Comment by psibernetic** [comment]
Since NancyHost is the consumer of the task it does need to capture context.

**Comment by thecodejunkie** [comment]
@khellang @damianh @grumpydev

**Comment by damianh** [comment]
Probably should be called from everywhere.

Explicit or assembly rewrite with a Fody plugin?

On 25 Aug 2016 12:51 p.m., "Andreas Håkansson" <notifications@github.com>
wrote:

@khellang <https://github.com/khellang> @damianh
<https://github.com/damianh> @grumpydev <https://github.com/grumpydev>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NancyFx/Nancy/issues/2471#issuecomment-242359437>, or mute
the thread

**Comment by horsdal** [comment]
I think line 133 should have a CAF.
Basically every `await` outside of tests should have a CAF AFAIK.

**Comment by thecodejunkie** [comment]
Been out of the loop a bit, but would adding that `ConfigureAwait` call fix #2534 ?

**Comment by jchannon** [comment]
What if you host by something else?

**Comment by thecodejunkie** [comment]
Well Nancy is a library and if you consume it yourself you are subjected to following the laws of async, this making sure you properly do your own `ConfigureAwait`-handling. Or am I thinking about this in the wrong way?

**Comment by damianh** [comment]
You are thinking about this in the correct way :)

**Comment by thecodejunkie** [comment]
@damianh so we should get this in, right?

**Comment by damianh** [comment]
Yep!

**Comment by thecodejunkie** [comment]
Oh wait.. this is an issue, not a pull-request.. @xt0rted mind sending a PR and I'll get it in asap?
