### ISSUE TITLE
Nancy selfhosting error on ubuntu with Mono

### ISSUE THREAD

**Issue by charleypeng** [NancyFx/Nancy#2487]
I am using Nancyfx as my restful api server. On windows I use Nancyfx in ASP.NET HOSTING MODE, all works fine on my App. But when I try to use a linux server, the app crushes as I use this code below

HttpClient client = new HttpClient();
HttpResponseMessage response = await client.GetAsync("http://ipaddress:1234/api/info");
response.EnsureSuccessStatusCode();
string responseBody = await response.Content.ReadAsStringAsync();
the exception here as below

An exception of type 'System.Net.Http.HttpRequestException' occurred in System.Net.Http.dll but was not handled in user code

Additional information: 500 (Internal Server Error) but when I use chrome to recieve the content, seems to work fine. Is there something wrong with my code or Nancyfx selfhosting mode?
Thanks!

**Comment by auxua** [comment]
Depending on your applications, this might be a problem of HttpClient-Headers.

I had the same problem and it could be fixed by explicitely adding a header for the "Accept"-header of your request.

Talking of code, you may try adding something like

`client.DefaultRequestHeaders.Accept.TryParseAdd("application/json");`

to your HttpClient request

Hopefully this helps

P.S.: There are other ways of adding Request Headers, but I think this is the best way doing it system-independently (tested with UWP, WP, Android, iOS and ASP.Net)

**Comment by charleypeng** [comment]
thanks , this problem solved by adding the header. thanks for the reply
