### ISSUE TITLE
Nancy ignores indirect descendants of the NancyModule which are in a dedicated assembly

### ISSUE THREAD

**Issue by energister** [NancyFx/Nancy#2569]
Say you have an assembly **A** in which you have a module:

```
public class MyModule : MyAbstractModule {}
```

The MyAbstractModule is in assembly **B**:

```
public abstract class MyAbstractModule : NancyModule {}
```

In this case Nancy will not discover MyModule because assembly A doesn't have reference to the Nancy assembly even if it has a class which is inherited from the NancyModule.

To fix this the discovery algorithm should become more complicated. It should also scan assemblies which has Nancy assembly somewhere in the assembly's dependency tree. In other words it should scan assemblies which references to the assemblies which references to the assemblies etc which in turn has a reference to the Nancy.

**Comment by jchannon** [comment]
Add this attribute in assembly A

https://github.com/NancyFx/Nancy/wiki/Bootstrapper#finding-the-right-bootstrapper

**Comment by thecodejunkie** [comment]
The problem here is that the linker quite often tries to be clever and sees that there is no direct reference to Nancy in the usage of types in A or B so it will simply remove Nancy in the list of references. It's a slippery slope to scan references or references etc. What about their references? And their references? How deep down the rabbit hole do you go before you can decide that there's nothing interesting to find? And at what start up cost?

It would literally mean we would have to scan ALL assemblies just to make sure there's no Nancy type hidden deeeeeeeep in there somewhere, which is exactly what we wanted to get away from as it has a serious impact on startup time
