### ISSUE TITLE
A constructor with a NameValueCollection argument causes StackOverflowException

### ISSUE THREAD

**Issue by ChangePlaces** [NancyFx/Nancy#2624]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

This started out as a [stackoverflow question](http://stackoverflow.com/questions/40701066/nancy-and-tinyioc-causing-stackoverflow)
In a nancymodule, when it has a constructor argument that can be resolved using a `NameValueCollection`, a `StackOverflowException` is thrown. I'm not sure if this is a TinyIoC issue or Nancy. Either way, it's a blocker when using external libraries with constructors with optional `NameValueCollection` argument

Tracing, shows that it's caught in a loop in `TinyIoC.cs` and `private IEnumerable<ConstructorInfo> GetTypeConstructors(Type type)` fetching constructors for `NameValueCollection` and `IHashCodeProvider`.  I have no idea why!

### Steps to Reproduce

	namespace NancyBugTest
	{
	    public interface IContext
	    {
		string Name { get; set; }
	    }

	    public class MyContext : IContext
	    {
		public string Name { get; set; }

		public MyContext() { }

		public MyContext(string name)
		{
		    this.Name = name;
		}

                // commenting this out prevents the stack overflow exception
		public MyContext(NameValueCollection props)
		{
		}
	    }

	    public class Foo : NancyModule
	    {
		public Foo(IContext c)
		{
		    
		}
	    }

	    class Program
	    {
		static void Main(string[] args)
		{
                   // stack overflow exception thrown here.
		    using (
			var host = new Nancy.Hosting.Self.NancyHost(new Uri("http://localhost:5555")))
		    {
			host.Start();
			Console.WriteLine("started self-host server");

			Console.ReadKey(true);
		    }
		}
	    }
	}

### System Configuration

- Nancy version:
1.4.3

- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
Windows 8.1
- .NET Framework version:
4.5

- Additional information:

**Comment by grumpydev** [comment]
This is because that constructor causes a cyclic dependency problem, whatever class has the constructor you will need to register manually, either using an instance or factor, or using the WithConstructor option which takes an expression to describe which constructor to use (assuming there's one without the NameValueCollection that works for you).

**Comment by ChangePlaces** [comment]
But, even if I register them, they still cause a cyclic problem?
            TinyIoCContainer.Current.Register<IContext, MyContext>();
            TinyIoCContainer.Current.Register<MyContext>(new MyContext());

**Comment by ChangePlaces** [comment]
Also, this is skirting around the real issue that the addition of the `NameValueCollection` causes a cyclic dependency whereas without it, there isn't one!

**Comment by grumpydev** [comment]
Nancy doesn't use TinyIoCContainer.Current, you need to register them in the bootstrapper as covered in the docs:

https://github.com/NancyFx/Nancy/wiki/Bootstrapping-nancy

**Comment by grumpydev** [comment]
It's not "skirting around" anything, there's no way for a container to resolve a dependency like that automatically, how does it know what is meant to be in that name value collection? It just makes zero sense as a constructor dependency if you're using a container (and makes virtually zero sense otherwise).

Specifically about NameValueCollection though, if you look at the constructors for that class, the only constructor it has that doesn't take "simple types" (ints etc, which the container can't hope to resolve) is a constructor that takes another NameValueCollection, which is the one the container tries to resolve automatically, but then its constructor takes a NameValueCollection.. rinse.. repeat - hence why it causes a stack overflow.

**Comment by ChangePlaces** [comment]
so, why can't the container filter down to resolve the `MyContext()` constructor because CanConstruct should detect it can't construct it?

**Comment by grumpydev** [comment]
The container tries to resolve the "greediest" constructor it can, so the one with the most number of arguments that it can probably resolve, it then tries to figure out whether it can resolve that dependency tree and blows up with the stack overflow (for the reasons described above).

To override that behaviour you use the options I mentioned above.

**Comment by ChangePlaces** [comment]
ok, thanks
