### ISSUE TITLE
Views outside of root path

### ISSUE THREAD

**Issue by mmaguigan-dti** [NancyFx/Nancy#2642]
### Description
I am attempting to force an application to adhere to the Linux File System Hierarchy, placing read-only static content such as views in /usr/share/myapp, state in /var/lib/myapp, etc., however, I am having difficulty giving NancyFX a fully qualified path via a custom view location convention. In browsing through the source code, I am afraid I may have fallen far from the *happy path*. Is directing Nancy toward paths outside of the configured root via rooted convention paths possible? Any guidance in accomplishing this without too much hackery would be greatly appreciated.

**Comment by thecodejunkie** [comment]
Hi,

Nancy has a concept known as [IViewLocationProvider](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ViewEngines/IViewLocationProvider.cs) which is responsible for gathering information about available view. The default one is called [FileSystemViewLocationProvider](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/ViewEngines/FileSystemViewLocationProvider.cs) and it, as the name suggests, located views that are located on the filesystem. The way it works is that is looks at on the file system, using the application root (provided by the current [IRootPathProvider](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/IRootPathProvider.cs)). 

You could of course implement your own root path provider and change root of your folder, but I would recommend against it since it would open up yourself to a lot of security concerns. It would be better for implement your own `IViewLocationProvider` and add your application specific implementation that satisfies your requirements.

Once you have that, you tell Nancy to use your own implementation by overriding `InternalConfiguration`, in your bootstrapper, and return `NancyInternalConfiguration.WithOverrides(x => x.ViewLocationProvider = typeof(YourOwnImplementation));`

Hope this helps
