### ISSUE TITLE
ConfigureRequestContainer vs ConfigureApplicationContainer

### ISSUE THREAD

**Issue by jruizaranguren** [NancyFx/Nancy#2670]
This is a question about defaults in IoC registration (not a bug).

I have read all google'able documentation about using the default container in Nancy, including [the wiki](https://github.com/NancyFx/Nancy/wiki/Bootstrapping-nancy), [stackoverflow](http://stackoverflow.com/questions/9571635/registering-dependencies-within-tinyioc-for-use-in-nancyfx/9572032#9572032), and [TinyIoC docs](https://github.com/grumpydev/TinyIoC/wiki).

First let's see if I understand correctly:

* When overriding `ConfigureApplicationContainer`, every registered interface will get a singleton lifetime, and every registered class type will get a multiple instance lifetime. The latter meaning each type request will get a new object. 
* When overriding `ConfigureRequestContainer`, the previous lifetimes are scoped to the request (à la Asp.Net).

And now some True/False? statements:

1. Modules are registered multi-instance, and are resolved just once per-request. Thus, if the dependency-tree of the module only need to resolve class types exactly once, then doing all registrations in `ConfigureApplicationContainer` achieves the same behavior than doing it in `ConfigureRequestContainer`. 
2. Following 1., if we add the `.AsMultiInstance()` extension to interface registrations, then we also get a resolution per request but only using `ConfigurationApplicationContainer` override. 
3. The default behavior of Nancy registration could be considered dangerous when registering interfaces in `ConfigureApplicationContainer` with types that hold state in a multi-threaded environment (asp.net). Typical example `MyBusinessThingsRepository`. Thread-safety should be analyzed for those types.
4. `ConfigureRequestContainer` is only needed when you need multiple resolutions of the same dependency within a single request, and you want the same object to be returned (i.e. singleton within the request).

If all above is right (miracle!), then I would say that default behavior and also "AutoRegister" is a bit confusing and could lead to mistakes in common cases (sharing a non-thread-safe object as a singleton).
It may be safer to default to multiple instance lifetime allways.
 
I suspect I am not considering cases where a dependency is resolved several times within the same request. It seems a pretty uncommon case that may be resolved with a third method extension (AsRequestSingleton()). Then a ConfigureRequestContainer would not be needed.

**Comment by khellang** [comment]
> When overriding `ConfigureApplicationContainer`, every registered interface will get a singleton lifetime, and every registered class type will get a multiple instance lifetime. The latter meaning each type request will get a new object.

Yes, this is correct, unless you explicitly specify the lifetime when you register stuff.

> When overriding `ConfigureRequestContainer`, the previous lifetimes are scoped to the request (à la Asp.Net).

The request container is a request-scoped container, that "inherits" the registrations from the application container. That means

 - Application singleton -> one single instance is resolved during the lifetime of the entire application
 - Application transient -> a new instance is always resolved each time
 - Request singleton -> one single instance is resolved during the lifetime of the request
 - Application transient -> same as "Application transient"

It also means that each of the registration lifetimes can resolve stuff from all the "scopes" above them in the list.

> Modules are registered multi-instance, and are resolved just once per-request. Thus, if the dependency-tree of the module only need to resolve class types exactly once, then doing all registrations in `ConfigureApplicationContainer` achieves the same behavior than doing it in `ConfigureRequestContainer`.

Modules [are registered as "request singletons"](https://github.com/NancyFx/Nancy/blob/692196b147fbc33e3c6d70372d3502969df71a4a/src/Nancy/DefaultNancyBootstrapper.cs#L162-L166), which means only one instance of a module will ever exist during the lifetime of a request. This doesn't really matter much, because Nancy will always just resolve a single instance of a module anyway.

> Following 1., if we add the `.AsMultiInstance()` extension to interface registrations, then we also get a resolution per request but only using `ConfigurationApplicationContainer` override.

`AsMultiInstance` (or as I call it; "transient") means that you get a new instance every time you ask for it. It doesn't matter whether these are registered in the application or request container.

> The default behavior of Nancy registration could be considered dangerous when registering interfaces in `ConfigureApplicationContainer` with types that hold state in a multi-threaded environment (asp.net). Typical example `MyBusinessThingsRepository`. Thread-safety should be analyzed for those types.

Yes. Singleton services live from they're first resolved until the application is killed. This means, if they have state, they should be thread-safe.

> `ConfigureRequestContainer` is only needed when you need multiple resolutions of the same dependency within a single request, and you want the same object to be returned (i.e. singleton within the request).

Yes, kinda. As mentioned earlier; transient registrations will always return a new instance, so it doesn't matter much if they're registered in the application- or request-scoped container. The only exception is if you have transient services that need access to other request-scoped services. Then you have to register them in the request container, because the registrations won't be available in the application container.

> I would say that default behavior and also "AutoRegister" is a bit confusing and could lead to mistakes in common cases (sharing a non-thread-safe object as a singleton).
> It may be safer to default to multiple instance lifetime allways.

To be honest, I'm not really sure how TinyIoC auto-registers stuff, because I've always disabled it (because of performance and control), but I guess you're right. I don't think we've received a lot of feedback on this, though, so I'm not sure it's a big problem. People generally tend to avoid keeping state in web applications these days.

> It seems a pretty uncommon case that may be resolved with a third method extension (AsRequestSingleton()). Then a ConfigureRequestContainer would not be needed.

Several containers (and bootstrappers) support this already. I.e. Autofac has a `InstancePerRequest` method.

**Comment by jruizaranguren** [comment]
Thanks, Kristian. I can not extend my experience to other projects, but It took me some time to figure this out. In particular, the default lifetime for objects in the registrations. If you think it might add some value I could try to improve the documentation at [Bootstrapping-nancy](https://github.com/NancyFx/Nancy/wiki/Bootstrapping-nancy).

**Comment by khellang** [comment]
> In particular, the default lifetime for objects in the registrations.

Yeah, personally I would never rely on either the implicit lifetimes, nor the auto-registration. It's just "too magic" to me. It's not my call, though :wink:

> If you think it might add some value I could try to improve the documentation at Bootstrapping-nancy.

Sure, knock yourself out! We always appreciate documentation work :heart:
