### ISSUE TITLE
HTTP/2 with Nancy

### ISSUE THREAD

**Issue by i2um1** [NancyFx/Nancy#2749]
Hi, how can I use HTTP/2 with Nancy?

**Comment by khellang** [comment]
It depends on your host. Since HTTP/2 is backwards compatible with HTTP/1.1 from an application POV, there's really not much to do, except finding a host that supports HTTP/2. For Nancy, that can be several alternatives; if you're running in IIS, you'll have HTTP/2 support in the newer versions. I also think there's HTTP/2 support in newer versions of `HttpListener` (because it uses HTTP.SYS, it should support same as IIS). Both Nancy's own `NancyHost` (self-host) and OWIN self-host uses `HttpListener`. If you want information on how to host Nancy with different alternatives, I suggest you see the documentation (wiki).

**Comment by i2um1** [comment]
Thanks, I found a solution. When I use `System.Net.Http.WinHttpHandler` it works with IIS 10 and NancyHost on latest windows 10 version.

**Comment by zdarova** [comment]
@i2um1 may I ask you, what was your solution more in detail? 
Thank you!

**Comment by i2um1** [comment]
I've used `System.Net.Http.WinHttpHandler` instead of the default. Probably, the issue is already fixed because it was 1 year ago.
