### ISSUE TITLE
Testing with the DefaultNancyBootstrapper fails because a root path provider cannot be created due to a missing parameterless constructor

### ISSUE THREAD

**Issue by lexmuc** [NancyFx/Nancy#2762]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy (clinteastwood NuGet package)
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode (only relevant for tests)
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am just starting a simple XUnit test using the default bootstrapper like this:

```
var bootstrapper = new DefaultNancyBootstrapper();
var browser = new Browser(bootstrapper);
```

### Steps to Reproduce
See description. Fails in the second line.

### System Configuration

- Nancy version: 2.0.0-clinteastwood
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: Nancy.Testing 2.0.0-clinteastwood
- Environment (Operating system, version and so on): Windows 7 Enterprise
- .NET Framework version: running with TargetFramework set to netcoreapp1.1
- Additional information:

**Comment by thecodejunkie** [comment]
Hi

The most likely explination for this is that you have your own `IRootPathProvider` implementation defined in one of the referenced projects. The `DefaultNancyBootstrapper` will be using the `IRootPathProvider` instance, that is located by the logic in the [GetRootPathProvider()](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L205) method of [NancyBootstrapperBase](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs)

It will scan for any implementation(s) of `IRootPathProvider` that does not exist in a `Nancy.*` namespace, and use that. If multiple implementations are found, it will end up throwing a `MultipleRootPathProvidersLocatedException` exception, containing a list of all the discovered bootstrappers. Since you are not getting this exception, it appears it is picking up a single instance.

The reasons that I believe that you have your own implementation are

1. You are not getting the `MultipleRootPathProvidersLocatedException`
2. The [DefaultRootPathProvider](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DefaultRootPathProvider.cs), which `DefaultNancyBootstrapper` would fall-back to using unless it found another implementation, does not define any constructors so that tell me that's not the implementation that Nancy is attempting to use

The one thing missing from your bug report is the stacktrace. It should be telling your which type is it failing to create an instance of, so my suggestion is that you go back and drill down to that and see which type is causing issues

**Comment by jpmnteiro** [comment]
I'm currently experiencing the same issue (`parameterless constructor`). 

I have a custom implementation of the interface, which I was registering in the IOC container (using Ninject, so `IKernel`). I would expect Nancy to look for a binding for `IRootPathProvider` there, but after digging around, it seems like it will ignore the container and just look on the non-Nancy assemblies and attempt to instantiate the type it finds (hence the exception, as my implementation has a parameter in the constructor).

Correct me if I'm wrong, but shouldn't it look in the container first and, if not available, fall back to the assembly search?
