### ISSUE TITLE
Nancy not triggering browser cancellation

### ISSUE THREAD

**Issue by RPM1984** [NancyFx/Nancy#2786]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I can't seem to get cancellations working correctly in Nancy, in particular passing the cancellationtoken from the module to Dapper.

I've replicated the issue by creating a simple Nancy app, adding a Dapper call with a simulated 'long' query.

When i hit the URL in the browser, then _stop_ the request, i would expect the cancellation to be triggered, and the Dapper query to be cancelled.

### Steps to Reproduce
1. Create a new Nancy web application (OWIN/Katana)
2. Add the following code (`HomeModule.cs`):

```
public HomeModule()
{
    Get["/slow-db", true] = async (p, ct) => await SlowDbAsync(ct);
}

private async Task<Response> SlowDbAsync(CancellationToken ct)
{
    using (var db = new SqlConnection(ConnectionString))
    {
        await db.QueryAsync(new CommandDefinition("WAITFOR DELAY '00:01'", cancellationToken: ct.Token, commandTimeout: 100));
    }
}
```

3. Run SQL profiler on your DB
4. Run the site, and hit the `slow-db` endpoint.
5. After a few secs, _cancel_ the browser request by using the cross action, or closing the browser etc
6. The query still runs for the full 60 secs.

If i add a manual `CancellationTokenSource` with a `CancelAfter` of say, a few seconds, it works fine and the query is cancelled in SQL profiler. So not sure why the Nancy `CancellationToken` isn't triggered the same way when the browser stops the event.

### System Configuration

- Nancy version: 1.4.4
- Nancy host
  - [] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): Windows
- .NET Framework version: 4.7
- Additional information:

**Comment by RPM1984** [comment]
Sorry, my mistake. I had the wrong hosting (`Nancy.Hosting.AspNet`. Should have been OWIN)

**Comment by PureKrome** [comment]
ping @phillip-haydon

**Comment by thecodejunkie** [comment]
Hi

Since you are hosting it on OWIN, this does fall into the category of "it's not us". Our OWIN bridge does pick up a passed in `CancellationToken` from the `owin.CallCancelled` environment variable (https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Owin/NancyMiddleware.cs#L98) and passes into Nancy (https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Owin/NancyMiddleware.cs#L98) during request handling.

So it really comes down to how your underlying OWIN server handels browser cancellation. So you need to read up on your server to see if it has that capability (for instance ASP.NET Core won't support it until 2.0).
