### ISSUE TITLE
Nancy CurrentUser is null when using MSOwin with cookies

### ISSUE THREAD

**Issue by generik0** [NancyFx/Nancy#2815]
### Description
Great software = NancyFx!
I have added NancyFx into a ASP.NET MVC project with OWIN, hosted in IIS and using it instead of webapi for the frontend. Unfortaunatley the context.CurrentUser is null. The ctx.GetMSOwinUser()?.Identity is not null.

Question: Should it?

If not, Is it possible to get the IoC/bootstrapper to resolve the CurrentUser  as the MsOwin User?. That wayi don't need to overwrite the autherization extensions.

- Nancy version: latest
- Nancy host
  - [X] Nancy.Owin (System.Web)

- .NET Framework version: 4.7
- Additional information: Autofac and AutofacNancyBootstrapper

**Comment by sphiecoh** [comment]
What authentication are you using ? 
Cookies ?
Stateless ?
Windows Auth?

**Comment by generik0** [comment]
Hi
Owin with cookies. Not statelse, not windows auth.
Just pure cookies.
ctx.GetMSOwinUser()?.Identity is working
ctx.CurrentUser is not providing a user.

If i make my own Auth extension like this below, i can autherize, but current user is always null:

`module.AddBeforeHookOrExecute(ctx =>
            {
                Response response = null;
                
                if (!ctx.GetMSOwinUser()?.Identity?.IsAuthenticated ?? true)
                {
                    response = new Response { StatusCode = HttpStatusCode.Unauthorized };
                }
                return response;
            }, "Requires Authentication");`

**Comment by generik0** [comment]
I tryied creating my own instance of IUserIdendity and letting the bootstrapper update the IUserIdendity to use my implemenation where the GetMSOwinUser is used.
However, no cigar. The Context's IUSerIdendity did not get updated. 

I think the easiest polase to do the override would be using the IoC. But what to change?

**Comment by xt0rted** [comment]
Nancy 1.4 doesn't have support for claims, that's why you have to use [Nancy.MSOwinSecurity](https://github.com/NancyFx/Nancy.MSOwinSecurity). Your options are to ignore the built-in auth entirely and stick with Nancy.MSOwinSecurity, or to try setting up custom code that will map the claims/user over to something Nancy can work with. As someone who has the exact setup as you I would recommend sticking with Nancy.MSOwinSecurity and forget all the built-in auth from Nancy. It's so much easier that way. If you really want Nancy knowing about your claims then you could try v2 since that has claims support, but it's also still a beta release.

**Comment by generik0** [comment]
Ok.
I have made my own extensions to use the ms owin and claims integration.
It works fine.
I will just keep this.
Thanks for your time :-)
