### ISSUE TITLE
Diagnostics wiki out of date - StaticConfiguration no longer contains EnableRequestTracing

### ISSUE THREAD

**Issue by piotrwojtowicz** [NancyFx/Nancy#2832]
StaticConfiguration no longer contains EnableRequestTracing so wiki is misleading: 
https://github.com/NancyFx/Nancy/wiki/Diagnostics#request-tracing

Proper sample is in: 
https://github.com/NancyFx/Nancy/blob/master/samples/Nancy.Demo.Hosting.Aspnet/DemoBootstrapper.cs#L40

```
public class DemoBootstrapper : DefaultNancyBootstrapper
{
    public override void Configure(INancyEnvironment environment)
    {
        environment.Tracing(
            enabled: true,
            displayErrorTraces: true);
    }
}
```

**Comment by thecodejunkie** [comment]
This is because of two reasons

1. 2.x isn't released in a stable version (even though 2.0-clinteastwood has been stable for quite some time and will be bumped to a stable build very soon)
2. And more importantly, GitHub doesn't easily let us version documentation so it would be a mess to intertwine 1.x and 2.x documentation. We're working with @daveaglick on improving our docs and as soon as that is done, we will put out 2.x updated documentation

HTH

/A
