### ISSUE TITLE
Date deserialization in Nancy 2

### ISSUE THREAD

**Issue by zszep** [NancyFx/Nancy#2902]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Upgrading from Nancy 1 to Nancy 2 I am facing a problem with binding date parameters. I am sending the following json payload from an angularjs app: { date=2018-04-30T22:00:00.000Z }

When binding the object with Nancy 2 it is converted to 30.04.2018 22:00:00. and not to 01.05.2018 00:00:00. How do I convert to the local (Croatian) time zone?

### System Configuration

- Nancy version: Nancy 2 Clint Eastwood
- Nancy host
  - [ ] Nancy.Hosting.Aspnet
  - [ ] Nancy.Hosting.Self
  - [x] Nancy.Owin (HttpListener)
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by sergeykonkin** [comment]
It probably doesn't apply to Nancy. When you call `DateTime.Parse` (in your case Nancy does it for you) it parses the date with `DateTimeKind.Local`. So you can basically call `ToUniversalTime()` method to convert your date to UTC date.

**Comment by sergeykonkin** [comment]
Oh, I missed the point of a question. If you want to receive Local time, you should pass date with appropriate time zone ("Z" in the end means it is UTC time). In your case, it will be "2018-04-30T22:00:00.000+0200".

**Comment by zszep** [comment]
@sergeykonkin Thanks for the suggestions. Your second comment seems to nail it. Looks like Nancy v1  parsed the date with DateTime.Local no matter the javascript format. There seems to be a breaking change in Nancy v2 where "T" and "Z" are taken into account and deserialized accordingly. I didn't change my javascript code but upgraded to v2 when the problem started.

**Comment by khellang** [comment]
@zszep I think the current behavior is more correct. You've explicitly specified that the offset is UTC (by appending 'Z' at the end). The difference is that now Nancy hands you back a universal `DateTime`, instead of converting it to local time.

I would suggest that you either

1. Move over to `DateTimeOffset` for better handling of offsets (this has been a recommendation for many many years).
2. Check the `DateTime.Kind` and adjust it according to your needs `ToLocalTime` or `ToUniversalTime`.

I think the change was introduced with the new JSON serializer in https://github.com/NancyFx/Nancy/pull/2313.
